<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_pb-8</name>
   <tag></tag>
   <elementGuidId>de949ce3-a5ce-44cb-93d3-d108c9ad2013</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='card-promo-promo-cicilan-0%-untuk-servis-di-auto2000']/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.pb-8</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>b8bca11e-484a-4a78-8c83-5a7dc86b9426</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>pb-8</value>
      <webElementGuid>6e5ddc0f-c779-4dcd-b64a-900c40987869</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;card-promo-promo-cicilan-0%-untuk-servis-di-auto2000&quot;)/div[@class=&quot;h-full border border-reliableBlack10 flex flex-col&quot;]/div[@class=&quot;pb-8&quot;]</value>
      <webElementGuid>52444e49-1cbd-4a6f-bbec-3a3268e3f30e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='card-promo-promo-cicilan-0%-untuk-servis-di-auto2000']/div/div</value>
      <webElementGuid>f65b38dd-20ec-4ec9-b044-8ef7dbf6233e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section[3]/div[2]/a/div/div</value>
      <webElementGuid>f0f22c14-cfb7-4d9c-a411-a7ef4d4b7706</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
