<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Field WHT</name>
   <tag></tag>
   <elementGuidId>d9888f82-e70a-4eec-8957-6be39800123f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;wht_percentage&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='wht_percentage']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>input[name=&quot;wht_percentage&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ea6858b9-a1df-42d9-a228-539cb3aeb6ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>95be76a9-c6bb-4f10-9572-16a041e79d2c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>wht_percentage</value>
      <webElementGuid>112b11d2-ac0c-442b-9b5f-ca1b57a119a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-full px-3 h-[52px] flex items-center placeholder:text-[#DEDEDE] focus:outline-none rounded-md w-[160px] false</value>
      <webElementGuid>05049a9a-416b-4d21-9d8f-ee5730260354</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>max</name>
      <type>Main</type>
      <value>100</value>
      <webElementGuid>5b14b508-0fe1-4105-8f45-4f45a005d5f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>91fb9169-f608-4974-a606-53c900a538f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;children-wrapper&quot;)/div[@class=&quot;flex justify-center&quot;]/div[@class=&quot;flex flex-col gap-7 w-[508px] md:w-full&quot;]/div[@class=&quot;pb-[100px]&quot;]/form[1]/div[@class=&quot;flex flex-col gap-7&quot;]/div[@class=&quot;flex flex-col gap-6&quot;]/div[@class=&quot;p-6 border border-[#F6F6F6] rounded-lg shadow-sm grid grid-cols-2 gap-x-6 gap-y-4&quot;]/div[@class=&quot;col-span-1 row-span-1&quot;]/div[@class=&quot;flex flex-col gap-2&quot;]/div[@class=&quot;flex justify-between items-center gap-2 mt-5 mb-4&quot;]/div[@class=&quot;flex gap-3 items-center&quot;]/div[1]/div[@class=&quot;relative w-full flex flex-col gap-1&quot;]/div[@class=&quot;flex items-center border border-[#DEDEDE] rounded-md text-black bg-white&quot;]/input[@class=&quot;w-full px-3 h-[52px] flex items-center placeholder:text-[#DEDEDE] focus:outline-none rounded-md w-[160px] false&quot;]</value>
      <webElementGuid>ccac54b1-73c4-427c-bb5c-d762011fa1e3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='wht_percentage']</value>
      <webElementGuid>5637e299-af40-4574-951e-aa1350187fdb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='children-wrapper']/div/div/div[2]/form/div/div/div/div[11]/div/div[3]/div/div/div/div[2]/input</value>
      <webElementGuid>2175ebd8-0b49-4e74-bd40-349bfdf8bef0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div[2]/input</value>
      <webElementGuid>3c59527e-5571-428f-85a0-64c02007dad3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'wht_percentage']</value>
      <webElementGuid>6d3c377b-7d13-47d9-8880-3c2d4b8870d5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
