<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Field NIS</name>
   <tag></tag>
   <elementGuidId>30aab0fb-438b-44f0-9190-fa0c50f15623</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='nis']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;nis&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Masukkan NIS&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>87a45231-4488-4c35-9dbd-5fd6caef927e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>6ca552d4-a3b0-464b-9ba2-e30be551a5af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Masukkan NIS</value>
      <webElementGuid>0d3dc919-2a23-4ca1-ac0a-f698cc575ee6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>h-full w-full rounded-md px-3 text-base placeholder:text-neutral6 focus:outline-none cursor-auto</value>
      <webElementGuid>fe1c0a4c-be64-40f8-bc41-090c4bf88a56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>nis</value>
      <webElementGuid>7c2e8a59-6976-447b-bb99-1fe4edcce3f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>2ebfdc81-39d9-49e0-89d5-c5f836ca1eb8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;layout-content&quot;)/div[@class=&quot;flex h-full flex-col overflow-auto&quot;]/div[@class=&quot;grow px-10&quot;]/form[1]/div[@class=&quot;grid grid-cols-2 gap-x-6 gap-y-4&quot;]/div[@class=&quot;flex gap-6&quot;]/div[@class=&quot;flex w-full flex-col gap-1&quot;]/div[@class=&quot;group relative flex h-[52px] w-full items-center gap-[10px] rounded-md border border-neutral5 bg-white focus-within:border-blue6 hover:border-blue6&quot;]/input[@class=&quot;h-full w-full rounded-md px-3 text-base placeholder:text-neutral6 focus:outline-none cursor-auto&quot;]</value>
      <webElementGuid>e8213e1f-aec0-4d1a-bb3e-c9cf6d3b1cc5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='nis']</value>
      <webElementGuid>cfe427ab-f3b3-44f0-a17f-4aa75f5665c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='layout-content']/div[2]/div/form/div/div[2]/div/div[2]/input</value>
      <webElementGuid>8c6f879d-76d5-46f3-bba0-f7f1ce1b90d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/input</value>
      <webElementGuid>3b640b15-92ea-4864-a449-75be62ee7f97</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'Masukkan NIS' and @name = 'nis']</value>
      <webElementGuid>bf202178-0183-4197-806b-03182c98943c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
