<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Radio Button Recurring Yes</name>
   <tag></tag>
   <elementGuidId>896331b5-920c-4279-8640-bf439af907b9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#yes</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='yes']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Yes&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>832fc4ae-0f21-4859-8247-b01f54c5a6cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>d77504f4-3698-4a48-a1ab-b62c83e0cac5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>yes</value>
      <webElementGuid>f910db77-a0fe-46eb-8929-0991275972a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-5 h-5 custom-radio cursor-pointer opacity-100</value>
      <webElementGuid>7c4d3d79-2795-4414-942d-88f69abf0326</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>recurring</value>
      <webElementGuid>2a42d30f-164d-40ca-879c-4cb18e35ab00</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>yes</value>
      <webElementGuid>464b0771-d1ba-4022-a73f-cb35c7d1362d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;yes&quot;)</value>
      <webElementGuid>ae9dc838-6784-41e9-a6b8-81168baed713</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='yes']</value>
      <webElementGuid>bcc4654a-10f6-4d45-bb6b-b9fe25a4d45e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='children-wrapper']/div/div/div[2]/form/div/div/div/div[9]/div/div/div[2]/div[2]/input</value>
      <webElementGuid>5ff1a7fc-f831-4ac6-85fb-16e2f657f8c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/div/div/div[2]/div[2]/input</value>
      <webElementGuid>5b085d2b-aab9-4bfa-bcab-16f687a42442</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @id = 'yes' and @name = 'recurring']</value>
      <webElementGuid>687a81db-dd92-45e6-aa7f-7effcfa5f55f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
