<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>inputbranch-input-fullname</name>
   <tag></tag>
   <elementGuidId>4b784875-c838-431b-9673-4f6b7e50047e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#branch-input-fullname</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='branch-input-fullname']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c52df2a8-4357-4e38-bef0-279cba024333</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>branch-input-fullname</value>
      <webElementGuid>02c63aac-1341-4af4-bb97-97356da1e4b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Nama Depan dan Belakang</value>
      <webElementGuid>196a128c-b53d-4896-aff6-fbad3128073b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>d43614cc-4298-446c-9066-e92dc3ff5572</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-full outline-none bg-reliableBlack3 bg-reliableBlack3 text-reliableBlack border-b border-reliableBlack30 placeholder:text-reliableBlack60 focus:border-reliableBlack60 false w-full px-4 py-2 lg:px-5 lg:py-4 max-h-[30px] lg:max-h-[40px] text-base lg:text-base leading-4 px-5 py-3.5 bg-reliableBlack3 border-[#5F5F5F] max-h-fit lg:max-h-fit focus:border-reliableBlack null  focus:outline-none</value>
      <webElementGuid>dace4917-45d2-4cf0-9061-6dabc7f0775b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;branch-input-fullname&quot;)</value>
      <webElementGuid>a471e005-68eb-48e7-a1e2-6cf705796fa3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='branch-input-fullname']</value>
      <webElementGuid>4f7cd10b-5c8c-44ea-bc8c-5a83944861a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//div[@id='branch-input-fullname-plp ']/div/div/div/input)[2]</value>
      <webElementGuid>5756e99d-ae97-4acc-ba23-e2048b1779c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/form/div/div/div/div/div/input</value>
      <webElementGuid>372e337f-84af-4271-9c4c-9733726873bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'branch-input-fullname' and @placeholder = 'Nama Depan dan Belakang' and @type = 'text']</value>
      <webElementGuid>882c4b9b-45ca-4ee3-b632-8e04980d2ab2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
