<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Button Checkbox</name>
   <tag></tag>
   <elementGuidId>5a34f375-cdd2-4f5d-89ab-216260c93c86</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='checkbox']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;checkbox&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;&quot;s</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>62f747e2-e0f1-4c2b-b19c-b5e9c8bf3794</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>4db1af49-1bba-4b5e-a283-4d0af80ca517</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>e2a003c7-3e9d-4764-9584-3c0295391077</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-5 h-5 border border-[#959595] rounded-[6px] focus:ring-0 checked:bg-red-600</value>
      <webElementGuid>60029ad7-997f-424e-9a45-d3f5b742eb1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;children-wrapper&quot;)/div[@class=&quot;fixed inset-0 bg-gray-800 bg-opacity-50 flex justify-center items-center z-[9999] overflow-y-auto&quot;]/div[@class=&quot;!max-w-[900px] !w-full overflow-x-hidden h-full max-w-[552px] m-4 lg:m-0 rounded-lg border border-[#D3D2D2] bg-white overflow-auto max-h-none md:max-h-[90vh] p-4 md:p-6 w-screen md:w-auto md:h-auto&quot;]/div[@class=&quot;flex flex-col h-full&quot;]/div[@class=&quot;flex flex-1 flex-col rounded-md border border-gray-200 mt-4 undefined&quot;]/div[@class=&quot;flex-col overflow-hidden w-full p-4 gap-4 bg-gray-50 grid flex-grow&quot;]/div[@class=&quot;flex gap-x-5&quot;]/div[@class=&quot;flex flex-col gap-4&quot;]/div[@class=&quot;flex gap-6 tablet-size:flex-col md:flex-row&quot;]/label[@class=&quot;flex gap-2 items-center text-sm font-medium&quot;]/input[@class=&quot;w-5 h-5 border border-[#959595] rounded-[6px] focus:ring-0 checked:bg-red-600&quot;]</value>
      <webElementGuid>49169f39-bd12-4989-a45b-0cdc46f5746f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='checkbox']</value>
      <webElementGuid>89ad843d-f20a-4b48-a549-3741eb2af239</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='children-wrapper']/div[2]/div/div[2]/div/div[2]/div[4]/div/div/label/input</value>
      <webElementGuid>c5fb83e7-25e7-432b-a825-d5c11bdf39eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label/input</value>
      <webElementGuid>48db9a30-268f-4be7-98ad-506aae85063a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @name = 'checkbox']</value>
      <webElementGuid>e6d18fd2-5a96-40aa-ad37-06baf0fcb478</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
