<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Button Pilih</name>
   <tag></tag>
   <elementGuidId>997dc8d5-bc07-4dbd-a256-cef51721bbba</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#id-pilih-variant</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;id-pilih-variant&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>c7787ded-00fb-45ff-9963-eb23d5d2b972</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>flex justify-end items-center p-3 gap-x-3 text-base font-bold md:p-4 md:justify-center md:flex-1 md:rounded     bg-supportiveRed text-white text-center w-full md:mt-8 p-5 md:p-4 h-[56px]</value>
      <webElementGuid>fb10b726-f728-4dda-8be7-dfeac9b0b837</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>id-pilih-variant</value>
      <webElementGuid>07d9af23-09b8-422a-9b3e-b2dbe69bac7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>variant</name>
      <type>Main</type>
      <value>bg-supportiveRed</value>
      <webElementGuid>59235227-4896-4a79-8e91-b11b955f4256</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Pilih</value>
      <webElementGuid>68abb017-1a76-491b-8bc3-d3b4d5355fd4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/main[@class=&quot;bg-white&quot;]/section[2]/div[@class=&quot;md:container py-4  px-0&quot;]/div[@class=&quot;opacity-100 duration-300 ease-in-out fixed w-[100vw] h-[100vh] z-[70] top-1/2 left-1/2 transform -translate-x-1/2 -translate-y-1/2 bg-opacity-30 bg-black&quot;]/div[@class=&quot;lg:max-h-[80vh] false duration-300 ease-in-out flex flex-col absolute bg-white rounded top-1/2 left-1/2 transform -translate-x-1/2 -translate-y-1/2&quot;]/div[@class=&quot;px-6 py-6 w-[622px]&quot;]/div[@class=&quot;flex flex-1 flex-col items-stretch w-full mx-auto md:mb-0 mb-4 md:mt-0 mt-3&quot;]/div[2]/button[@id=&quot;id-pilih-variant&quot;]</value>
      <webElementGuid>b47c871d-eb86-42bc-b70a-2973d2611504</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='id-pilih-variant']</value>
      <webElementGuid>7324152e-3e9b-4afe-8c3a-c92b00c22168</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/main/section[2]/div/div[2]/div/div[2]/div/div[2]/button</value>
      <webElementGuid>72051e92-8991-4d50-8491-195cc6022f1e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='HUBUNGI ACCOUNT EXECUTIVE KAMI'])[1]/following::button[1]</value>
      <webElementGuid>b309ac22-29ef-421b-996b-90c7a9ccd9e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bingung memilih tipe yang sesuai?'])[1]/following::button[1]</value>
      <webElementGuid>e6223461-c087-41c1-8b5e-83605df3c202</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='UNDUH KATALOG'])[1]/preceding::button[1]</value>
      <webElementGuid>56c837f3-0be8-4087-a0f4-3e7e3e52950b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/button</value>
      <webElementGuid>8a9e1d1f-e5f6-4971-af64-ca472c334312</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'id-pilih-variant' and (text() = 'Pilih' or . = 'Pilih')]</value>
      <webElementGuid>6094be8d-2b6c-452b-bff5-28438ce35007</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
