<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Manual 1</name>
   <tag></tag>
   <elementGuidId>d3c5141f-3122-420e-bcc2-174adaa16df1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//input[@id=&quot;radio-MANUAL-1&quot;])</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#radio-0</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9d3113aa-ae46-447b-b3f6-ea5484c7f102</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>radio-0</value>
      <webElementGuid>9fb86667-6ed8-43e6-ad45-e10108a57110</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>b1b5be4d-c3c4-466d-afe6-863aff4d3692</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>radio-options</value>
      <webElementGuid>c214e6d5-ca67-4ed0-be16-b37ba15b56ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-4 h-4 text-[#231F20] bg-gray-100 md:mt-0  mt-2 focus:ring-[#4F4C4D]</value>
      <webElementGuid>9b77ed7e-7ce3-4e14-be4d-c8bdcd85277b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>B101GM/T02_T1E7</value>
      <webElementGuid>c2450548-f3e6-4865-89e6-40749eb349bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/main[@class=&quot;bg-white&quot;]/section[2]/div[@class=&quot;md:container py-4  px-0&quot;]/div[@class=&quot;opacity-100 duration-300 ease-in-out fixed w-[100vw] h-[100vh] z-[70] top-1/2 left-1/2 transform -translate-x-1/2 -translate-y-1/2 bg-opacity-30 bg-black&quot;]/div[@class=&quot;lg:max-h-[80vh] false duration-300 ease-in-out flex flex-col absolute bg-white rounded top-1/2 left-1/2 transform -translate-x-1/2 -translate-y-1/2&quot;]/div[@class=&quot;px-6 py-6 w-[622px]&quot;]/div[@class=&quot;flex flex-1 flex-col items-stretch w-full mx-auto md:mb-0 mb-4 md:mt-0 mt-3&quot;]/div[@class=&quot;flex flex-col flex-1 items-stretch&quot;]/ul[@class=&quot;lg:h-[30vh] h-auto flex-col overflow-scroll md:space-y-3 md:mt-2 text-[14px] text-gray-700 md:mb-8 mb-10&quot;]/li[@class=&quot;md:border-b md:border-[#C6C6C6] last:border-none&quot;]/div[@class=&quot;flex wrapper-radio-filter md:items-center py-2 md:px-4 px-2 gap-2&quot;]/input[@id=&quot;radio-0&quot;]</value>
      <webElementGuid>c4d83d8f-6969-4ef7-abd0-c62931d60a45</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='radio-0']</value>
      <webElementGuid>5f75628c-7a5e-49e5-82a8-a682f4801ce8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/main/section[2]/div/div[2]/div/div[2]/div/div/ul/li/div/input</value>
      <webElementGuid>0e32b366-379b-4241-994b-b0119f67b043</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/div/input</value>
      <webElementGuid>39fb9956-345b-4123-b68d-25119dff24e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'radio-0' and @type = 'radio' and @name = 'radio-options']</value>
      <webElementGuid>c5c7e9a0-5a75-4e10-8824-6e40687c12a5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
