<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Model Manual</name>
   <tag></tag>
   <elementGuidId>0164e0b8-9801-47a0-987d-91e4793f5297</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;__next&quot;]/main/section[2]/div/div[2]/div/div[2]/div/div/div[1]/div/div[2]/div[2]/label</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>4c525f97-f770-4556-9257-ce3216175ab7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>894cb93a-07db-44bb-92d9-ec6db4416318</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>block w-full text-[14px] uppercase cursor-pointer font-medium select-none rounded-[4px] text-center peer-checked:bg-[#231F20] peer-checked:font-semibold peer-checked:text-white text-[#606060] h-8 flex flex-col justify-center</value>
      <webElementGuid>467279ae-3d24-443e-99e3-f5bbdc728b83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Manual</value>
      <webElementGuid>f997c52d-5467-42d2-9087-c6d25aa56d46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/main[@class=&quot;bg-white&quot;]/section[2]/div[@class=&quot;md:container py-4  px-0&quot;]/div[@class=&quot;opacity-100 duration-300 ease-in-out fixed w-[100vw] h-[100vh] z-[70] top-1/2 left-1/2 transform -translate-x-1/2 -translate-y-1/2 bg-opacity-30 bg-black&quot;]/div[@class=&quot;lg:max-h-[80vh] false duration-300 ease-in-out flex flex-col absolute bg-white rounded top-1/2 left-1/2 transform -translate-x-1/2 -translate-y-1/2&quot;]/div[@class=&quot;px-6 py-6 w-[622px]&quot;]/div[@class=&quot;flex flex-1 flex-col items-stretch w-full mx-auto md:mb-0 mb-4 md:mt-0 mt-3&quot;]/div[@class=&quot;flex flex-col flex-1 items-stretch&quot;]/div[@class=&quot;w-full md:mb-0 mb-4 md:mt-0 mt-3&quot;]/div[@class=&quot;flex flex-1 flex-row gap-2 rounded-[8px] bg-[#F4F4F4] p-1 md:mb-5 mb-1&quot;]/div[@class=&quot;w-full items-center justify-center&quot;]/label[@class=&quot;block w-full text-[14px] uppercase cursor-pointer font-medium select-none rounded-[4px] text-center peer-checked:bg-[#231F20] peer-checked:font-semibold peer-checked:text-white text-[#606060] h-8 flex flex-col justify-center&quot;]</value>
      <webElementGuid>8943f687-5e14-4c56-b2ee-c7d46111db51</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/main/section[2]/div/div[2]/div/div[2]/div/div/div/div[2]/div[2]/label</value>
      <webElementGuid>b983e383-296f-403a-8817-056ea903e507</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Otomatis'])[1]/following::label[1]</value>
      <webElementGuid>42bf2129-99a9-48a4-967c-f517219f6c26</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pilih Transmisi'])[1]/following::label[2]</value>
      <webElementGuid>685362cf-5c5d-4e72-8bc7-d88ab451f8ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='AGYA 1.2 G A/T TRD'])[1]/preceding::label[1]</value>
      <webElementGuid>bc2edfc2-d69e-4786-904d-e51a059b7c21</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='NEW AGYA 1.2 G A/T'])[1]/preceding::label[2]</value>
      <webElementGuid>c0be2120-1779-49f0-acd3-238b3d187a50</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Manual']/parent::*</value>
      <webElementGuid>9ad66027-0f1e-4469-9579-7af1772eb475</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/label</value>
      <webElementGuid>13c20a70-d43f-417f-a6f0-e55b610a2cee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = 'Manual' or . = 'Manual')]</value>
      <webElementGuid>ee208b89-3c5e-4207-8e7a-9488020735b1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
