<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Hubungi Kami</name>
   <tag></tag>
   <elementGuidId>cc9d4ab9-7350-4c25-855a-108ab2002f39</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#nav-call</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='nav-call']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>8698afcc-a08c-4788-b87b-96d027ad893d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>nav-call</value>
      <webElementGuid>238325d6-b3d7-4e1e-bbe9-3171e9ab8e1a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://auto2000.co.id/hubungi-kami</value>
      <webElementGuid>3d8a79e7-0d04-4339-b7cc-15c7635a80aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>flex text-reliableBlack items-center gap-1 px-3 h-10</value>
      <webElementGuid>7ee50cd0-383b-4b46-8439-b67e0057c805</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Hubungi Kami</value>
      <webElementGuid>4fb84a3c-0b6e-4c25-9fe7-ab0cffc0770c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nav-call&quot;)</value>
      <webElementGuid>f0783c34-1094-45e5-b0e6-dcacf2913e18</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='nav-call']</value>
      <webElementGuid>a1f8a949-4f3c-40fe-b092-62a1ee4acdee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/nav/div/div/a</value>
      <webElementGuid>7850fab8-9cc6-472d-88b4-b960bca0b4b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://auto2000.co.id/hubungi-kami')]</value>
      <webElementGuid>52cd0c0e-969b-4f0f-9ebe-2726e706087a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a</value>
      <webElementGuid>ce7c69b2-4b9c-4edd-83b6-2c0e2681fe05</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'nav-call' and @href = 'https://auto2000.co.id/hubungi-kami' and (text() = 'Hubungi Kami' or . = 'Hubungi Kami')]</value>
      <webElementGuid>d0219a3b-6e16-43e9-ad84-41f1916a19c4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
