<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Button Petunjuk Arah</name>
   <tag></tag>
   <elementGuidId>9a2687b5-9e59-4a95-96fe-7218265a0607</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id='branch-direction-pdp']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#branch-direction-pdp</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>efdb755d-ac9d-4a40-b897-a4ecadea7f3f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>branch-direction-pdp</value>
      <webElementGuid>a5bbedb0-4fe6-426c-aa29-d54cda499487</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://www.google.com/maps/dir/'-6.2455808,106.9907968'/-6.174593,106.855087</value>
      <webElementGuid>4f6ba2a5-5ea2-40e3-b5ee-cc3d54cf9f02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_blank</value>
      <webElementGuid>f96ae2ca-f145-4cbd-a671-9568e073e65d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rel</name>
      <type>Main</type>
      <value>noopener</value>
      <webElementGuid>4492ea1c-81a7-4881-987c-6cdfc7d5b01c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>order-3 lg:order-none flex items-center text-xs text-hyperLink mt-2</value>
      <webElementGuid>77abb5ff-cabf-40ac-be2f-0dd95dac643a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Petunjuk Arah (16.95 Km)</value>
      <webElementGuid>4e9a5c95-0bda-483c-b628-84e316e5b9c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;branch-direction-pdp&quot;)</value>
      <webElementGuid>8469b407-e8fc-45e1-b902-a46f12bfa1b9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='branch-direction-pdp']</value>
      <webElementGuid>a750cad9-3371-4278-8590-3e4b6b183e4c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/main/div[2]/section/div[3]/div/div/a</value>
      <webElementGuid>a3b5f6b9-6b5c-4d4c-9853-1c09dd2d444a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Jl. Letjen. Suprapto'])[1]/following::a[1]</value>
      <webElementGuid>5395657f-3382-4c50-a06c-b416bbebe8d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Auto2000 Cempaka Putih'])[4]/following::a[1]</value>
      <webElementGuid>c6d98e84-1eee-4aa7-a856-c7ba25be00cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='(021) 4262000'])[1]/preceding::a[1]</value>
      <webElementGuid>57a3e295-7971-4749-aa5d-41561622a844</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='JAM OPERASIONAL'])[1]/preceding::a[2]</value>
      <webElementGuid>1a2b9975-144e-47df-8a17-3d8b6a5d0210</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Petunjuk Arah']/parent::*</value>
      <webElementGuid>cb285d1b-ff72-4a60-8e69-598f7ef0f28c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, &quot;https://www.google.com/maps/dir/'-6.2455808,106.9907968'/-6.174593,106.855087&quot;)]</value>
      <webElementGuid>a28df0ea-3215-4c04-98a5-9f3faf0553a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/a</value>
      <webElementGuid>ecd65ab6-e3a8-4d6d-806d-4174196169d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'branch-direction-pdp' and @href = concat(&quot;https://www.google.com/maps/dir/&quot; , &quot;'&quot; , &quot;-6.2455808,106.9907968&quot; , &quot;'&quot; , &quot;/-6.174593,106.855087&quot;) and (text() = ' Petunjuk Arah (16.95 Km)' or . = ' Petunjuk Arah (16.95 Km)')]</value>
      <webElementGuid>cd774c87-4a3c-4dbf-8d67-7c96537b5ffc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
