<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Table Action</name>
   <tag></tag>
   <elementGuidId>7fc407be-7300-4a80-be52-83a37fcee1fe</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@data-testid = 'table-action-1']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#table-action-1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='table-action-1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>[data-testid=&quot;table-action-1&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>d144e958-8262-4a43-96bc-25c882e9bcd1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>table-action-1</value>
      <webElementGuid>c3e5a756-be6b-4827-a111-f1a07667db46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>table-action-1</value>
      <webElementGuid>4e9b1294-96c0-4e03-9bd2-496af252ae2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>bg-primary5 absolute top-9 -translate-x-full translate-y-4 rounded-md border-neutral4 bg-white p-1 shadow-sm</value>
      <webElementGuid>6d7da412-bc62-42e7-894e-86de8a510e8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>EditLihat</value>
      <webElementGuid>d5528a41-3f4a-44fa-87fd-63a708431c7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;table-action-1&quot;)</value>
      <webElementGuid>6095074e-923c-47da-a2e6-440eb56559a9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='table-action-1']</value>
      <webElementGuid>6fb1f36f-c851-431e-acda-4239055fa915</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div[3]</value>
      <webElementGuid>4085ebc6-ec28-4ff3-8aa4-1b7f7991f772</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='of'])[2]/following::div[12]</value>
      <webElementGuid>c1b4be13-edc1-4b2e-98e9-2d065e8aa26b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Page'])[1]/following::div[12]</value>
      <webElementGuid>58dd9797-8292-464e-824c-4140d61ceac1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]</value>
      <webElementGuid>bd8436c7-e151-4f53-886b-2e3750b8355b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'table-action-1' and (text() = 'EditLihat' or . = 'EditLihat')]</value>
      <webElementGuid>05b2c745-86eb-431a-94a8-0429ce5ca1f0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
