<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Field Provinsi</name>
   <tag></tag>
   <elementGuidId>d13f436a-2a2a-4f59-8f6d-08b98d308a00</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#dd-provinsi</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='dd-provinsi']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Pilih Provinsi&quot;s]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>838adc54-db51-4676-a780-3f95805d7b6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dd-provinsi</value>
      <webElementGuid>3c0cb8f5-b93e-41d5-b6e7-0298a252ee98</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>bc4897a6-42a4-4a56-9b47-bada1f6a22b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-full outline-none px-4 py-2 bg-reliableBlack3 placeholder:text-reliableBlack60 text-reliableBlack border-b border-reliableBlack30 focus:border-reliableBlack60 lg:px-5 lg:py-4 !bg-white border-[#5F5F5F] max-h-fit lg:max-h-fit focus:border-reliableBlack false disabled:text-reliableBlack50 disabled:bg-reliableBlack10 cursor-pointer</value>
      <webElementGuid>b0b0234b-9da8-4f3d-bad5-8b8cdd61ed37</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Pilih Provinsi</value>
      <webElementGuid>1c2122aa-2ff0-424c-9df0-4c8079916141</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>DKI Jakarta</value>
      <webElementGuid>35f3a96d-dca6-454f-8ad0-36c350f6cc83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dd-provinsi&quot;)</value>
      <webElementGuid>565a1233-3b63-4e83-9a96-c99dd18ecf4a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='dd-provinsi']</value>
      <webElementGuid>b72cc77c-80a5-4eec-b85a-464f52e17a54</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/main/div[3]/div/div/div[2]/section/form/div[2]/div/div/input</value>
      <webElementGuid>749113d2-eb95-4e73-901a-b809eaabb872</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/input</value>
      <webElementGuid>96664a28-ec91-4221-9b87-f2e5e2cf9bd4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'dd-provinsi' and @type = 'text' and @placeholder = 'Pilih Provinsi']</value>
      <webElementGuid>b77a56f7-1376-48de-8c70-11869fb6614d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
