<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Field No Hp</name>
   <tag></tag>
   <elementGuidId>e43e98c7-6bd3-4287-a854-7a6c1ccd72f0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input-phone-number</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input-phone-number']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;XXX-XXX-XXX&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1edb2b7a-814e-4a3d-8819-d3faa7393731</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-phone-number</value>
      <webElementGuid>58da4119-660e-4b17-ab8d-59c1cfe214e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>XXX-XXX-XXX</value>
      <webElementGuid>3cbbfaef-7987-4805-a9b9-c4130b2d2504</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>345a16d2-44d5-4309-8b22-fd8780e3f4a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-full outline-none null bg-reliableBlack3 text-reliableBlack border-b border-reliableBlack30 placeholder:text-reliableBlack60 focus:border-reliableBlack60 false w-full px-4 py-2 lg:px-5 lg:py-4 max-h-[30px] lg:max-h-[40px] text-base lg:text-base leading-4 !bg-white border-[#5F5F5F] max-h-fit lg:max-h-fit focus:border-reliableBlack false !pl-1 null  focus:outline-none</value>
      <webElementGuid>6ba6ee2a-9c87-440f-8353-304c3c4fb34e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>pattern</name>
      <type>Main</type>
      <value>[0-9]*</value>
      <webElementGuid>a7e36505-a5eb-4404-88d6-9344c3b17d16</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>inputmode</name>
      <type>Main</type>
      <value>numeric</value>
      <webElementGuid>cf7580fe-69af-4ecc-aed3-57792698e79a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>min</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>b8af99d6-136d-41fb-966b-629a9e820297</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-phone-number&quot;)</value>
      <webElementGuid>2e893b4c-d60f-4c7a-914f-89e40d20b863</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-phone-number']</value>
      <webElementGuid>7d603d7d-42e0-480d-97e6-d86850054fe0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/main/div[3]/div/div/div[2]/section/form/div/div[2]/div/div/div/input</value>
      <webElementGuid>10bd92eb-0d39-4b04-a23f-ce30eb46acee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div[2]/div/div/div/input</value>
      <webElementGuid>44114418-e39b-41e5-a737-fb5ffae29f94</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'input-phone-number' and @placeholder = 'XXX-XXX-XXX' and @type = 'number']</value>
      <webElementGuid>948df71d-518a-4ed1-a734-df6a827ff9ae</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
