<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Button Pre Order</name>
   <tag></tag>
   <elementGuidId>316828aa-a484-4b54-815a-2c3623f83ad6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#id-beli-mobil</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='id-beli-mobil']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>d3b8dcf7-9c7b-47de-af37-42e053a54c8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>id-beli-mobil</value>
      <webElementGuid>5c59e1c6-615c-44de-b4e9-59024a1b5aac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>relative flex whitespace-nowrap justify-center items-center px-4 gap-x-1.5 font-semibold bg-supportiveRed  h-[52px] text-base leading-[22px] rounded    text-white !bg-reliableBlack md:px-0 px-4 w-full !text-[14px] btn-primary-white bookbtn btn-bookOrBuy btn-book-buy-new-pdp</value>
      <webElementGuid>84303e04-ec8d-44d4-b22d-b541f61598f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>d1cd2dfc-4c01-4526-b520-edc5ea4da1f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>PRE ORDER</value>
      <webElementGuid>9307111a-2dfc-4262-9450-82e2e0e2ae67</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;id-beli-mobil&quot;)</value>
      <webElementGuid>a4bd2127-852c-4e5a-8c55-1b3c3da0bb95</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='id-beli-mobil']</value>
      <webElementGuid>3b6904f2-9702-4662-8924-bfc453eff290</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/main/section[2]/div/div[3]/div[2]/div[2]/div/a/button</value>
      <webElementGuid>df2d224c-c4b0-4e2c-9810-71b84eb8c26b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SIMULASI KREDIT'])[1]/following::button[1]</value>
      <webElementGuid>372a47f0-1d73-4f5b-b152-cc5aa709780a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='UNDUH KATALOG'])[1]/following::button[2]</value>
      <webElementGuid>53072562-53e9-45a6-b464-ac66a78685cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SIMULASI KREDIT'])[2]/preceding::button[1]</value>
      <webElementGuid>2300866a-d2a8-467e-ac9f-8e67fe8ce8e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/button</value>
      <webElementGuid>f5d12823-e983-420a-b57c-ba86068d9edb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'id-beli-mobil' and @type = 'submit' and (text() = 'PRE ORDER' or . = 'PRE ORDER')]</value>
      <webElementGuid>a3139ab6-74a4-45e4-9440-fb275c036758</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
