<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Kategori Spesifikasi</name>
   <tag></tag>
   <elementGuidId>61714382-62ea-42be-be40-e9a0d3114350</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#id-ncp-spesifikasi</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='id-ncp-spesifikasi']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>23fe124b-a406-433c-a52a-e0098e858fd2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>id-ncp-spesifikasi</value>
      <webElementGuid>6bb92328-90c4-4624-ba98-8025ea1e52db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>flex items-center text-xs uppercase text-reliableBlack whitespace-nowrap py-3.5 px-4 border-b-4 lg:text-base lg:py-4 lg:px-5 lg:border-b-[3px] hover:border-supportiveRed border-transparent</value>
      <webElementGuid>9b0a6bf0-8574-4c8a-af92-02f1610859d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>SPESIFIKASI</value>
      <webElementGuid>b3b6ef18-c1d8-4aad-b27b-c8a47cba6591</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;id-ncp-spesifikasi&quot;)</value>
      <webElementGuid>49bdcbf4-cfd9-40ca-a168-fb39f6f5bc0f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='id-ncp-spesifikasi']</value>
      <webElementGuid>c9113634-b7fe-447a-958e-8b8a6930787a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/main/section/div/ul/li[2]/div/a/div</value>
      <webElementGuid>0f978b59-f7ae-415d-b0b8-f09f35ac2bb5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='OVERVIEW'])[2]/following::div[2]</value>
      <webElementGuid>194fb178-bfa7-4f7a-ba41-d89e63a262c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='OVERVIEW'])[1]/following::div[5]</value>
      <webElementGuid>782e90f7-d88f-4eed-bc56-e49ab37a6940</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='INTERIOR'])[1]/preceding::div[1]</value>
      <webElementGuid>f9f22ff8-b125-4a0b-b0da-75b87f91868a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/div/a/div</value>
      <webElementGuid>c19e4724-e903-4231-bd8e-86b78db7a8c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'id-ncp-spesifikasi' and (text() = 'SPESIFIKASI' or . = 'SPESIFIKASI')]</value>
      <webElementGuid>320ef334-268f-4b58-b51a-251b11e05e05</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
