<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Field Nomor NPWP</name>
   <tag></tag>
   <elementGuidId>47e97770-64c0-444b-91b6-2b836ad41bc7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#npwpNumber</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='npwpNumber']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Masukkan nomor pokok wajib pajak&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4e3fe5c9-484c-49db-a6fb-10fb88c621a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>1d25a8f4-96c5-463d-bd59-8a9c99b1245e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>npwpNumber</value>
      <webElementGuid>44dd8231-9921-42a4-9687-04ea70dd534e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Masukkan nomor pokok wajib pajak</value>
      <webElementGuid>74461df0-769e-4b36-b5d2-7d47c85a7887</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-full px-3 h-[52px] flex items-center placeholder:text-gray-400 focus:outline-none rounded-md  false</value>
      <webElementGuid>c4be294e-1054-4121-9c9f-202f31454939</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>max</name>
      <type>Main</type>
      <value>100</value>
      <webElementGuid>08828d15-4294-4ff3-92d0-2472671449d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>npwpNumber</value>
      <webElementGuid>a39cd9d7-beec-4182-92bd-bb6aceecfeaf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>092542943407000</value>
      <webElementGuid>03930d4f-cb32-4647-800a-3b8b47d1e56c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;npwpNumber&quot;)</value>
      <webElementGuid>fc1c51a4-09a8-4a48-acb4-864ed4800a3e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='npwpNumber']</value>
      <webElementGuid>c584b8b4-ee89-474d-a65e-4567f3a9b83f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='children-wrapper']/div/div[4]/form/div/div[2]/div/div/div[2]/div/div[2]/div/div[2]/input</value>
      <webElementGuid>b3a8a6d6-e1aa-45cd-85ab-555a2fd57b72</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/form/div/div[2]/div/div/div[2]/div/div[2]/div/div[2]/input</value>
      <webElementGuid>8c2f6d16-cc63-4549-a67d-28c898c1b602</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'npwpNumber' and @placeholder = 'Masukkan nomor pokok wajib pajak' and @id = 'npwpNumber']</value>
      <webElementGuid>fb043f8d-e068-4981-aab3-b4efa693ebf3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
