<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Field Nama Lengkap NPWP</name>
   <tag></tag>
   <elementGuidId>e7098762-8b2f-4f64-b489-041e74cb01f8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#npwpName</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='npwpName']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Masukkan nama lengkap&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a9c1e6cd-c0c7-4f12-a4d7-3091f5646c5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>f3ca1bd0-4e35-4baf-8138-3897fd779843</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>npwpName</value>
      <webElementGuid>117ce5ff-2488-4754-8899-7a33c7991ec2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Masukkan nama lengkap</value>
      <webElementGuid>5eed12ee-a263-485c-a0ad-e9dcc905e255</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-full px-3 h-[52px] flex items-center placeholder:text-gray-400 focus:outline-none rounded-md  false</value>
      <webElementGuid>7dac5263-5069-48d2-acf6-7efbc1d0ae98</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>max</name>
      <type>Main</type>
      <value>100</value>
      <webElementGuid>3de6a697-fff9-411d-aa34-1d27cfba34cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>npwpName</value>
      <webElementGuid>e11cc256-20dd-4a52-ac59-0ca735a414b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Henri Prasetyo</value>
      <webElementGuid>58634ee2-d6d7-4446-b16f-492975bed41c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;npwpName&quot;)</value>
      <webElementGuid>f36ea679-5926-492e-8b87-fde35d62728d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='npwpName']</value>
      <webElementGuid>6c324910-3639-4835-a22e-60c466e11f4b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='children-wrapper']/div/div[4]/form/div/div[2]/div/div/div[2]/div/div/div/div[2]/input</value>
      <webElementGuid>8f02722d-a579-473f-949e-4b3d3a780ff3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/form/div/div[2]/div/div/div[2]/div/div/div/div[2]/input</value>
      <webElementGuid>18b3d84b-c135-4467-b8ee-3cf296d21288</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'npwpName' and @placeholder = 'Masukkan nama lengkap' and @id = 'npwpName']</value>
      <webElementGuid>44b42e41-1ee8-457f-95f5-29f29b27b4ef</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
