<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Button Lihat Semua AE</name>
   <tag></tag>
   <elementGuidId>808a4df4-0c4f-4c04-8bfc-588ea3968178</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='all-salesman']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#all-salesman</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>fef15365-2c06-492e-9e00-601ae8aec3e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>all-salesman</value>
      <webElementGuid>d5136642-00c2-4f46-b4f4-504efaaa4889</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>flex items-center gap-2 lg:gap-4</value>
      <webElementGuid>6510e5bd-f45a-45ef-9dae-29e4061b87fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Lihat Semua</value>
      <webElementGuid>217531e6-7c85-402d-9607-4b9798296486</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;all-salesman&quot;)</value>
      <webElementGuid>3681d565-2c74-412c-bb5c-fcc38a0b382d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='all-salesman']</value>
      <webElementGuid>77242684-982c-4309-962f-346c629bf283</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/main/div[2]/section[2]/div/div/a/span</value>
      <webElementGuid>ad5e1095-319b-4690-8b7a-499c252c1ae9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lihat Semua'])[1]/following::span[1]</value>
      <webElementGuid>e9ff094e-f5b9-4f01-927b-9372af403f67</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ingin Konsultasi?'])[1]/following::span[2]</value>
      <webElementGuid>64430dda-de14-4165-9287-406c1760fd8c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ZULXXXXXNDI'])[1]/preceding::span[1]</value>
      <webElementGuid>f5ad2fcb-2ef0-4856-8d3b-e9b91b866608</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='MINTA PENAWARAN'])[1]/preceding::span[1]</value>
      <webElementGuid>c490ae7d-eb51-4dde-8d22-454d150f1681</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/a/span</value>
      <webElementGuid>e9ff743c-e9a1-497e-8e5e-5f071e1fc2d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'all-salesman' and (text() = 'Lihat Semua' or . = 'Lihat Semua')]</value>
      <webElementGuid>575b34e3-232d-4b53-b74c-16ee5e35fcc0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
