<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>inputdd-model-mobil</name>
   <tag></tag>
   <elementGuidId>daa290b9-ce7d-4159-bcea-3c3a25aa6dda</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;dd-model-mobil&quot;]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#dd-model-mobil</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>175303c5-f6e9-4ed0-8cee-2fee9b8d6b19</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dd-model-mobil</value>
      <webElementGuid>d93113ca-01a6-4d72-ba20-35612a49c0a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>d3cc67bf-0045-4a74-9f6b-ec69082f2bd0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-full outline-none px-4 py-2 bg-reliableBlack3 placeholder:text-reliableBlack60 text-reliableBlack border-b border-reliableBlack30 focus:border-reliableBlack60 lg:px-5 lg:py-4 !bg-white border-[#5F5F5F] max-h-fit lg:max-h-fit focus:border-reliableBlack false cursor-pointer</value>
      <webElementGuid>8c02e4aa-f50a-4d83-949f-bfbabdf9facf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Pilih Mobil</value>
      <webElementGuid>d37c533c-62fa-4302-bb5f-c62350ce44cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dd-model-mobil&quot;)</value>
      <webElementGuid>3890103a-ea42-4678-8632-42910de7a145</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='dd-model-mobil']</value>
      <webElementGuid>30ee3713-8795-45f4-9b7e-b43a4bd5c093</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/main/div[3]/div/div/div[2]/section/form/div[4]/div/div/input</value>
      <webElementGuid>4b1f588c-95ff-4dc5-801f-641088c95924</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div[4]/div/div/input</value>
      <webElementGuid>dbec3090-e368-439d-adb6-c618fae9858c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'dd-model-mobil' and @type = 'text' and @placeholder = 'Pilih Mobil']</value>
      <webElementGuid>ebe74d66-4075-427b-a64e-c514c61bb48c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
