<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Kode OTP 4</name>
   <tag></tag>
   <elementGuidId>1822eb8d-6cbb-4313-8a3e-ac3132251b23</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@type='text' and @maxlength='1'])[4]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>input:nth-child(3)</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f7044eb3-c9fa-4945-a723-649d0623e5ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>7c96e8aa-b38d-45ca-bc32-24864d4eba72</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>f309d9b1-42b4-4230-99bb-80e6e972e7c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-[60px] h-[52px] text-center text-xl border border-[#DEDEDE] rounded focus:outline-none focus:ring-2 focus:ring-blue-500</value>
      <webElementGuid>cd4ab4ba-0dd6-488f-a8b2-b5b4c8b8f9a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>a96922d5-0185-41a5-b48d-aebf7b99f8de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;flex justify-end md:justify-end items-center bg-cover bg-center global-bg&quot;]/div[@class=&quot;rounded-lg&quot;]/div[@class=&quot;bg-white p-10 rounded-lg mx-[73px] my-8 max-h-[800px] flex flex-col overflow-auto&quot;]/div[@class=&quot;flex-grow&quot;]/div[@class=&quot;flex flex-col gap-[20px]&quot;]/div[@class=&quot;flex flex-col gap-10&quot;]/div[1]/div[@class=&quot;flex gap-3 mt-2&quot;]/input[@class=&quot;w-[60px] h-[52px] text-center text-xl border border-[#DEDEDE] rounded focus:outline-none focus:ring-2 focus:ring-blue-500&quot;]</value>
      <webElementGuid>b0bf17ed-3c25-40ba-9ba0-a8c2b90e8d3a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@value='1'])[3]</value>
      <webElementGuid>642da9bd-bbfa-4e73-ae5b-c8c4057b791e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div[2]/div/div/div[2]/div/div/div/div/input[3]</value>
      <webElementGuid>6a5d698c-16b1-436d-b928-5a060af17c5a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[3]</value>
      <webElementGuid>8e5105fb-2eb1-4f97-ab1f-623fbd798ad5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text']</value>
      <webElementGuid>4863b64d-663b-4fe5-9cb9-4a603a9225a7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
