<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Kode OTP 5</name>
   <tag></tag>
   <elementGuidId>f9c01143-b9c5-4cb0-a243-7324b11fa2b4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@type='text' and @maxlength='1'])[5]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>input:nth-child(5)</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3e292a44-c64b-40fa-a86a-f540872942c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>f37a0324-bc38-4c01-afa8-728a6235fc81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>2aaa3887-4310-4af9-8714-462325391f70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-[60px] h-[52px] text-center text-xl border border-[#DEDEDE] rounded focus:outline-none focus:ring-2 focus:ring-blue-500</value>
      <webElementGuid>623d1181-01bc-4403-921c-4acca5a880b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>f7e084d6-15c7-4360-be76-9646790e603f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;flex justify-end md:justify-end items-center bg-cover bg-center global-bg&quot;]/div[@class=&quot;rounded-lg&quot;]/div[@class=&quot;bg-white p-10 rounded-lg mx-[73px] my-8 max-h-[800px] flex flex-col overflow-auto&quot;]/div[@class=&quot;flex-grow&quot;]/div[@class=&quot;flex flex-col gap-[20px]&quot;]/div[@class=&quot;flex flex-col gap-10&quot;]/div[1]/div[@class=&quot;flex gap-3 mt-2&quot;]/input[@class=&quot;w-[60px] h-[52px] text-center text-xl border border-[#DEDEDE] rounded focus:outline-none focus:ring-2 focus:ring-blue-500&quot;]</value>
      <webElementGuid>f4d77725-fb0b-4e6f-b022-8c5718a6b55c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@value='1'])[5]</value>
      <webElementGuid>7d04ef4b-ac13-4e10-89f5-9fe7f7c017dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div[2]/div/div/div[2]/div/div/div/div/input[5]</value>
      <webElementGuid>d24669ff-4a97-4dee-876f-b0247d11d0c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[5]</value>
      <webElementGuid>9f58ac64-8762-411c-99c1-6ce36ef5ff04</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text']</value>
      <webElementGuid>85c6719f-d4cd-49d4-898b-fc22d4eeaa53</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
