<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Button Masuk Login</name>
   <tag></tag>
   <elementGuidId>307b177b-e302-499e-b26b-55fa3b198a48</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@type='submit']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Masuk&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>bcb8f877-34fb-4ddc-9bc8-8a940b712eb1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>f6f2cf66-678e-4e87-83f2-0aa48454eb56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>cursor-pointer rounded-md flex gap-1 justify-center py-[8px] items-center bg-[#5D1472] px-[24px] bg-[#5D1472] !text-white bg-primaryColor text-white text-[16px] font-medium px-4 rounded-md w-full justify-center py-3   false</value>
      <webElementGuid>73b95a7c-b311-4ccb-a75e-c3f68809c908</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Masuk</value>
      <webElementGuid>1f37edf1-bc62-422f-a365-a9c79492e56a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;__className_d65c78&quot;]/div[@class=&quot;flex flex-row justify-center overflow-x-hidden lg:max-h-screen w-full&quot;]/div[@class=&quot;flex flex-1 flex-col w-full lg:w-full&quot;]/div[@class=&quot;flex flex-1 justify-center items-center text-center&quot;]/div[@class=&quot;flex flex-1 bg-cover bg-center max-h-screen&quot;]/div[@class=&quot;rounded-lg flex flex-1&quot;]/div[@class=&quot;flex flex-1 flex-col w-full&quot;]/div[@class=&quot;flex flex-1 p-10 !mb-6 h-full min-w-[50wh] lg:pt-[128px] lg:px-[156px] !pt-0 px-8 flex-col mb-8&quot;]/div[@class=&quot;flex-grow flex flex-1&quot;]/div[@class=&quot;flex flex-1&quot;]/form[@class=&quot;flex flex-1 flex-col gap-8&quot;]/div[@class=&quot;flex flex-col gap-y-4&quot;]/button[@class=&quot;cursor-pointer rounded-md flex gap-1 justify-center py-[8px] items-center bg-[#5D1472] px-[24px] bg-[#5D1472] !text-white bg-primaryColor text-white text-[16px] font-medium px-4 rounded-md w-full justify-center py-3   false&quot;]</value>
      <webElementGuid>cbf8da2b-a3be-445f-9362-105e83bddd7b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@type='submit']</value>
      <webElementGuid>5cf7b41e-e5de-4726-ab70-92e0465445ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div/div[2]/div[2]/div/div/div/div[2]/div[2]/div/form/div[3]/button</value>
      <webElementGuid>c57a530b-ccce-4e1f-bc78-8b6ca8b15faf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Password'])[1]/following::button[1]</value>
      <webElementGuid>cadad908-c1dc-49ca-a23c-3b0d99bd1d85</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nomor HP / Email'])[1]/following::button[1]</value>
      <webElementGuid>4f173e62-3969-4a57-a709-b2d6521ccfca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Klik Di sini'])[1]/preceding::button[1]</value>
      <webElementGuid>1a5a1a69-2803-452f-a1ec-e00346be78b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>a1c735f0-69c1-42c0-86d3-167aec6502d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and (text() = 'Masuk' or . = 'Masuk')]</value>
      <webElementGuid>135a96fc-e0a7-4abb-87a3-acc93b105db3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
