<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Model Mobil</name>
   <tag></tag>
   <elementGuidId>5c4bfaed-4f9f-4242-8a9c-1cc65e47528a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#dd-model-mobil</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='dd-model-mobil']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1fff5431-a5e2-45e7-88c0-8d599532fd0b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dd-model-mobil</value>
      <webElementGuid>14c2e2fd-eaf0-4183-ba2b-275502f5282d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>0f5bf48c-9b6f-45f0-9950-ff9644bc2793</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-full outline-none px-4 py-2 bg-reliableBlack3 placeholder:text-reliableBlack60 text-reliableBlack border-b border-reliableBlack30 focus:border-reliableBlack60 lg:px-5 lg:py-4 bg-white border-[#5F5F5F] max-h-fit lg:max-h-fit focus:border-reliableBlack false cursor-pointer</value>
      <webElementGuid>d684189e-6667-4927-b263-ac1906e1c2e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Pilih Mobil</value>
      <webElementGuid>527ffc45-4884-49a0-b37c-ddcb31b91da5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dd-model-mobil&quot;)</value>
      <webElementGuid>25814625-9dc6-4209-a45c-e0a9fa80be52</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='dd-model-mobil']</value>
      <webElementGuid>7bd47e96-a916-481e-8211-3a5b6da84717</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/main/div[2]/div/div/div[2]/div/section/form/div[2]/div/div/input</value>
      <webElementGuid>a6b5d061-b6f2-426d-a956-9cf6d2d75ce3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/input</value>
      <webElementGuid>55c0847f-b0de-4f09-bb00-3ef13f362bd2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'dd-model-mobil' and @type = 'text' and @placeholder = 'Pilih Mobil']</value>
      <webElementGuid>e585c2e4-29f3-46d9-8832-b26e3b7174a2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
