<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_MINTA PENAWARAN</name>
   <tag></tag>
   <elementGuidId>c5326868-4b9f-4e21-b501-722432beeed4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#offering</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='offering']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>2792752a-c05b-4529-8e59-9f96aa2397c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>relative flex whitespace-nowrap justify-center items-center px-4 gap-x-1.5 font-semibold bg-reliableBlack90  h-[52px] text-base leading-[22px] rounded    text-white w-full mt-6</value>
      <webElementGuid>22495c1c-9258-4fbb-bc31-3a97e041176c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>fdf9ecac-3414-425a-8884-27d88275d630</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>offering</value>
      <webElementGuid>70099309-7c0f-40df-9fef-b38e3c5be22d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>MINTA PENAWARAN</value>
      <webElementGuid>6e027b34-3092-4932-bfcf-a70a3dac6b25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;splide02-slide01&quot;)/div[@class=&quot;px-4 lg:px-0 md:px-4 pb-4&quot;]/button[@id=&quot;offering&quot;]</value>
      <webElementGuid>331dba83-3ab1-4066-95ad-cadde7648ab0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='offering']</value>
      <webElementGuid>d6fb0a85-6e44-4175-a53d-4a173791bd98</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='splide02-slide01']/div[3]/button</value>
      <webElementGuid>c8f6f6e4-993c-485a-b54f-4b708d91d9dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/div[3]/button</value>
      <webElementGuid>9899bbdb-6143-478d-9b82-41c082667f88</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and @id = 'offering' and (text() = 'MINTA PENAWARAN' or . = 'MINTA PENAWARAN')]</value>
      <webElementGuid>9adabf69-4c22-40fd-a7bd-98ec413917f6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
