<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>inputproduct-dd-province</name>
   <tag></tag>
   <elementGuidId>0c7ce920-5a25-4f4b-82be-f51f729c9019</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#product-dd-province</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='product-dd-province']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>fe260661-6b0c-40d1-b8a1-137cf0610fca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>product-dd-province</value>
      <webElementGuid>958948c9-cf37-4b9d-9e90-6fce5715e06b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>29e21645-c663-4bc9-8bda-2876c79f63de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-full outline-none px-4 py-2 bg-reliableBlack3 placeholder:text-reliableBlack60 text-reliableBlack border-b border-reliableBlack30 focus:border-reliableBlack60 lg:px-5 lg:py-4 px-5 py-3.5 text-reliableBlack max-h-fit bg-reliableBlack3 placeholder:text-[#777777] lg:max-h-fit lg:text-reliableBlack cursor-pointer</value>
      <webElementGuid>3ff9fc73-03a7-4614-bd2d-5c38541a0403</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Pilih Provinsi</value>
      <webElementGuid>2528ca2e-9603-427f-b773-047f50263e42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;product-dd-province&quot;)</value>
      <webElementGuid>d71199f8-00fe-4bae-b6ea-b7f909c88bce</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='product-dd-province']</value>
      <webElementGuid>f12eb18c-cfcc-4452-a249-47192e0ff7ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/main/div[8]/div/div[2]/form/div[2]/div/div/input</value>
      <webElementGuid>9477891e-3f0c-4800-8e95-fea54fbe79d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/input</value>
      <webElementGuid>e246d236-c37d-4bbd-94e6-eb20d9363b67</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'product-dd-province' and @type = 'text' and @placeholder = 'Pilih Provinsi']</value>
      <webElementGuid>a055fc82-4ca5-4a7d-bd35-af861551c941</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
