<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Kabupaten Jember</name>
   <tag></tag>
   <elementGuidId>0bf710c2-1d2c-4541-9e01-051f2f6069c4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='dd-form-kabupaten-jember
              ']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>1452d493-d7bc-4248-9974-fc2d7d6abe3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dd-form-kabupaten-jember
              </value>
      <webElementGuid>c4a8e305-ce21-4a34-a694-55b91b205755</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>px-4 py-2 hover:bg-gray-100 cursor-pointer</value>
      <webElementGuid>77c7d465-0079-4169-a851-a3314a865ce8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Kabupaten Jember</value>
      <webElementGuid>07428e73-dec8-4df1-917c-d3bfea0e3443</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dd-form-kabupaten-jember
              &quot;)</value>
      <webElementGuid>3eb24037-8eb8-46a3-90c5-4533f2f7f486</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='dd-form-kabupaten-jember
              ']</value>
      <webElementGuid>42e16f62-90b5-41a9-af99-40d51fe70634</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/main/div[8]/div/div[2]/form/div[3]/div/ul/li[3]</value>
      <webElementGuid>30d9287a-fdf1-4e0c-8c92-5df6dcd3115d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/ul/li[3]</value>
      <webElementGuid>9fc77972-80d3-4d3b-8a68-a7f553d7d689</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'dd-form-kabupaten-jember
              ' and (text() = 'Kabupaten Jember' or . = 'Kabupaten Jember')]</value>
      <webElementGuid>524de230-026e-4adb-84d6-4096fca755a2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
