<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Button Terbitkan</name>
   <tag></tag>
   <elementGuidId>c7f1dd1d-eb50-4fb2-8f2a-e5834492b06e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[text()='TERBITKAN']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;TERBITKAN&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>7a798004-f907-49ea-b203-14c90cb656d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>6a284905-6c26-49eb-959c-75eb6fa68b3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-reliableBlack90 bg-red-600 text-white py-2 px-4 tracking-wide border border-transparent text-[16px] font-bold mt-2 md:mt-0 md:ml-2 </value>
      <webElementGuid>6a13817a-ebdb-4538-adb5-7042c7f7b63f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>TERBITKAN</value>
      <webElementGuid>e53a70b9-b26f-4d68-80a0-3367d91c7155</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/main[@class=&quot;relative&quot;]/div[@class=&quot;bg-gray-100 text-gray-800&quot;]/div[@class=&quot;container relative&quot;]/div[2]/div[1]/div[1]/div[@class=&quot;px-12 gap-2&quot;]/form[1]/div[@class=&quot;flex items-center justify-between fixed bottom-0 z-50 bg-white shadow py-6 px-8 transition-all duration-100 h-[80px] left-[320px] w-[calc(100%-320px)]&quot;]/div[@class=&quot;mb-2 md:mb-0 flex ml-auto&quot;]/button[@class=&quot;text-reliableBlack90 bg-red-600 text-white py-2 px-4 tracking-wide border border-transparent text-[16px] font-bold mt-2 md:mt-0 md:ml-2&quot;]</value>
      <webElementGuid>1c9e2181-fe6a-41bc-9332-6285c1cc2454</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[13]</value>
      <webElementGuid>0f5ae093-4ebe-4936-a449-44a234cb05ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/main/div[2]/div/div[2]/div/div/div/form/div[4]/div[2]/button[2]</value>
      <webElementGuid>777cfbe6-c076-4592-aa7c-de8ad35a4184</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PRATINJAU'])[1]/following::button[1]</value>
      <webElementGuid>14b5e535-02a9-45e4-988c-c04972f493aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SIMPAN DRAFT'])[1]/following::button[2]</value>
      <webElementGuid>35dffcf1-65b6-4194-a44c-2dcc85dbe66d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='TERBITKAN']/parent::*</value>
      <webElementGuid>1de29c3b-0f8c-4ac4-80e7-8a6b1a0daf12</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/button[2]</value>
      <webElementGuid>77606c84-8dcb-405d-a5f8-ae79b465023e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'TERBITKAN' or . = 'TERBITKAN')]</value>
      <webElementGuid>6d325daf-7788-401c-9208-1bbd2f9a06c3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
