<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Field Provinsi</name>
   <tag></tag>
   <elementGuidId>fe85f194-481c-48e3-8768-5bc142d23334</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.select__value-container.css-hlgwow</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='province']/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>div >> internal:has-text=/^Provinsi$/ >> nth=2</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>71c4b53b-4c11-4c8a-b1c1-5d05a45c72ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select__value-container css-hlgwow</value>
      <webElementGuid>ee7e1530-4fa1-41ce-a8dc-fca4f13ec297</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Provinsi</value>
      <webElementGuid>4c1b5c6a-0a52-4c2b-b1cc-f8e392c0ddcd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;province&quot;)/div[@class=&quot;select__control css-13cymwt-control&quot;]/div[@class=&quot;select__value-container css-hlgwow&quot;]</value>
      <webElementGuid>9bf74a76-3a6a-4eba-8157-5f48cc22c363</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='province']/div/div</value>
      <webElementGuid>9c4486a8-aabe-43b8-b532-f2f5ec67b2ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Provinsi'])[1]/following::div[3]</value>
      <webElementGuid>aca9d04f-b4bc-477b-92e9-a65c4cfc8ea6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pengaturan Lokasi'])[1]/following::div[6]</value>
      <webElementGuid>7ce03c13-7cd5-49fa-a384-2b91aad0b134</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kota'])[1]/preceding::div[5]</value>
      <webElementGuid>01113764-39b6-49c3-abb7-c96eb6646d96</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[2]/div/div/div/div/div/div/div/div</value>
      <webElementGuid>6ff8d6cc-9d38-4274-bb46-9b712785f4cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Provinsi' or . = 'Provinsi')]</value>
      <webElementGuid>9c2a21d9-e4a8-4662-9e10-2bf262b6a28b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
