<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Radio Button Trade</name>
   <tag></tag>
   <elementGuidId>5848f09a-c028-4bca-ba1a-8ef932c3ab04</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#trade</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='trade']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Trade&quot;s</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7473dba5-5e9a-4d71-abb8-51eb25cdc087</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>10f558e2-5efe-4a07-901e-4f718cfc09d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>trade</value>
      <webElementGuid>ee12ca1a-9ed5-4ff4-88e6-e03c7b5788a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-5 h-5 custom-radio cursor-pointer opacity-100</value>
      <webElementGuid>68f62d8a-e645-4234-8ce6-7be9d50f1c84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>type_filter</value>
      <webElementGuid>3946d063-23ad-4ae2-95f7-69096c14ef3f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>trade</value>
      <webElementGuid>b7a2e640-b771-463f-9bce-c1fc5713d65d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;trade&quot;)</value>
      <webElementGuid>afc9ee49-5355-4f66-a474-a05c6f582bfc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='trade']</value>
      <webElementGuid>ec1096df-43f9-4537-bce8-ca2154a00ce7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='children-wrapper']/div/div/div/div[2]/div/div[4]/div/div[2]/form/div/div/div/div[2]/div/input</value>
      <webElementGuid>e36b3c2e-cb11-4faf-9ada-2a175ab7ada5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/input</value>
      <webElementGuid>adfab2e0-9b98-4026-b3ff-fd13ec5f31e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @id = 'trade' and @name = 'type_filter']</value>
      <webElementGuid>b81230ee-c34d-4574-a1d8-2178fe36946f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
