<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Radio Button Non Trade</name>
   <tag></tag>
   <elementGuidId>46312a65-415c-4c21-b05b-9ad7c998c47b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#non-trade</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='non-trade']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Non-Trade&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c84c4a7b-1b07-4aab-a0cc-c0e3da2ce782</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>5abe4c15-1910-49d2-8dc8-bf18b201e958</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>non-trade</value>
      <webElementGuid>36d3a5ee-1d5b-430b-98d9-ac2943c316b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-5 h-5 custom-radio cursor-pointer opacity-100</value>
      <webElementGuid>d4ebb9d3-4dda-4adb-afa6-12ec14f7f751</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>type_filter</value>
      <webElementGuid>ffee1d6a-217c-4233-bc5b-96e269385114</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>non-trade</value>
      <webElementGuid>41b7730f-d9a2-4161-91c9-0e04da62243d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;non-trade&quot;)</value>
      <webElementGuid>2a521847-ec52-4d1d-9199-5e079a526090</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='non-trade']</value>
      <webElementGuid>08e6ccc3-07fc-4884-afb2-a98c45680d77</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='children-wrapper']/div/div/div/div[2]/div/div[4]/div/div[2]/form/div/div/div/div[2]/div[2]/input</value>
      <webElementGuid>199a1bd3-12d7-4af9-b4af-2233d5b4724f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>c0394f65-fc3b-4697-b6a0-30e63cb48e26</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @id = 'non-trade' and @name = 'type_filter']</value>
      <webElementGuid>4d79f645-46df-44c0-8c46-6d1d9e5ca225</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
