<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Button Pilih</name>
   <tag></tag>
   <elementGuidId>b601da0d-fce2-4260-b3df-3ea69dd8a174</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#id-pilih-variant</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='id-pilih-variant']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>2e501fa3-3bc7-4956-b6b0-fa79f73d1c84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>flex justify-end items-center p-3 gap-x-3 text-base font-bold md:p-4 md:justify-center md:flex-1 md:rounded     bg-supportiveRed text-white text-center w-full mt-[50px] md:mt-8 p-5 md:p-4</value>
      <webElementGuid>2fb44db2-7562-4cd4-be15-761de60d76e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>id-pilih-variant</value>
      <webElementGuid>6ac6b41e-251a-42ce-a961-d8a8097cf4df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>variant</name>
      <type>Main</type>
      <value>bg-supportiveRed</value>
      <webElementGuid>0eaa4ed1-7629-473d-9596-3c281077f223</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Pilih</value>
      <webElementGuid>8d07ca11-5daf-490a-bdd4-2b8920c26c75</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;id-pilih-variant&quot;)</value>
      <webElementGuid>dd2d6ec3-eeb4-49d9-83b6-b660b2e29038</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='id-pilih-variant']</value>
      <webElementGuid>dc783ccd-0f20-4d67-a157-acd70f263f4f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/main/section[2]/div/div[2]/div/div[2]/div/section/div[2]/button</value>
      <webElementGuid>96fef032-d7b9-44d2-abed-62a904f9337c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='HUBUNGI ACCOUNT EXECUTIVE KAMI'])[1]/following::button[1]</value>
      <webElementGuid>10f0409c-d13c-40ae-8352-a9562945d6ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bingung memilih tipe yang sesuai?'])[1]/following::button[1]</value>
      <webElementGuid>4651ed9b-ac29-4b20-a9ea-ad1af0b3e3d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='AUTO2000 ©'])[1]/preceding::button[1]</value>
      <webElementGuid>68ad0d33-5f6d-4daa-bee4-9f5bad3f3a63</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section/div[2]/button</value>
      <webElementGuid>4c37ac67-cee7-4dd8-b2a9-4f4116a6405c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'id-pilih-variant' and (text() = 'Pilih' or . = 'Pilih')]</value>
      <webElementGuid>be7d585b-6762-4ad5-acce-f606e9685f45</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
