<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Manual 1</name>
   <tag></tag>
   <elementGuidId>e456cdcc-ad98-4f97-859d-afea9a045d48</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#radio-0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='radio-1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a0daa4cf-2247-4ea5-8e97-2781de01c9e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>radio-0</value>
      <webElementGuid>d7e677d3-109d-40c6-a7a5-945e3d37e443</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>928c4ae0-cee8-48a0-b60e-579feee5b581</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>radio-options</value>
      <webElementGuid>3a030aa8-5b9f-4bd0-a9db-ff6d176d83d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-4 h-4 text-[#231F20] bg-gray-100 md:mt-0  mt-2 focus:ring-[#4F4C4D]</value>
      <webElementGuid>c8425b9b-f4b8-4de3-8916-4e0e4873add2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>B101GM/T02_T1E7</value>
      <webElementGuid>28a6ec8f-e448-4e83-a6ce-b2fdedfd0486</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;radio-0&quot;)</value>
      <webElementGuid>c5e138b0-20f3-4d22-a8f0-e139f70cfec6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='radio-0']</value>
      <webElementGuid>90e76333-1f85-4db8-90af-3f90010cb4be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/main/section[2]/div/div[2]/div/div[2]/div/section/div/div[2]/ul/li/div/input</value>
      <webElementGuid>b0a283f6-72a6-4b49-9991-b81f60850ee2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/div/input</value>
      <webElementGuid>6a6ee867-6b0d-4c37-8c4a-189991cce200</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'radio-0' and @type = 'radio' and @name = 'radio-options']</value>
      <webElementGuid>c97d184c-8efe-40ff-9c13-c77ec8f13a1e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
