<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Otomatis 1</name>
   <tag></tag>
   <elementGuidId>6ca26cc9-62bf-4480-b94a-ef173d2fc422</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#radio-0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@class='flex flex-1 flex-col items-stretch w-full mx-auto md:mb-0 mb-4 md:mt-0 mt-3']//input[@id='radio-0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7f07d3b7-7a6f-4de3-bfb6-b78bc9b1130f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>radio-0</value>
      <webElementGuid>603671be-9435-4fe3-a268-f5024fafe451</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>fc57da28-b5d4-4993-b379-a54ded4b23bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>radio-options</value>
      <webElementGuid>0c70ac01-6e1c-45d7-93ba-a382956f9f94</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-4 h-4 text-[#231F20] bg-gray-100 md:mt-0  mt-2 focus:ring-[#4F4C4D]</value>
      <webElementGuid>615b760e-fded-447f-a65d-9110ea061ec6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>B101GA/T02_T1E7</value>
      <webElementGuid>e1932c5b-933a-4bce-9c81-8532fb44c32f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;radio-0&quot;)</value>
      <webElementGuid>25050bd0-a2f6-4d40-bf0a-6c1a9a78431c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='radio-0']</value>
      <webElementGuid>c979d256-4cfe-4e3a-a81c-8c24491f1257</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/main/section[2]/div/div[2]/div/div[2]/div/section/div/div[2]/ul/li/div/input</value>
      <webElementGuid>e4bb411a-b1e0-441c-bf6f-1a3cc6633700</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/div/input</value>
      <webElementGuid>610dda3e-6f26-4262-8ad6-f91ac796039b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'radio-0' and @type = 'radio' and @name = 'radio-options']</value>
      <webElementGuid>25f47524-ea5b-44d6-84bc-f7ef81493385</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
