<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Field Provinsi</name>
   <tag></tag>
   <elementGuidId>61efffc4-4a70-4af1-9c82-940ff42b875f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#dd-provinsi</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='dd-provinsi']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Pilih Provinsi&quot;s]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>33933461-071e-4c62-a87a-e4475b06086a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dd-provinsi</value>
      <webElementGuid>4d708f72-5b4e-445e-8b3a-cd16bf696500</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>692d9c39-25b4-4032-bafc-8ea1050c0ffa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-full outline-none px-4 py-2 bg-reliableBlack3 placeholder:text-reliableBlack60 text-reliableBlack border-b border-reliableBlack30 focus:border-reliableBlack60 lg:px-5 lg:py-4 !bg-white border-[#5F5F5F] max-h-fit lg:max-h-fit focus:border-reliableBlack false disabled:text-reliableBlack50 disabled:bg-reliableBlack10 cursor-pointer</value>
      <webElementGuid>989df7b4-8c3c-40b5-ba1b-c7509bd28534</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Pilih Provinsi</value>
      <webElementGuid>c1a24a75-aa00-4edd-8f11-6c3638192021</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>DKI Jakarta</value>
      <webElementGuid>ea32d94a-c135-495c-9e74-a7f1b9e74330</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dd-provinsi&quot;)</value>
      <webElementGuid>32a909d3-7f3c-4c87-a0a4-9c6d99b46268</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='dd-provinsi']</value>
      <webElementGuid>166e013a-b515-4414-aba4-44fd13180140</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/main/div[3]/div/div/div[2]/section/form/div[2]/div/div/input</value>
      <webElementGuid>8ca5c7b6-b348-4ed0-801e-f7bb34781136</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/input</value>
      <webElementGuid>832735f6-c7f9-4f1f-bbc1-2e9922e4fa4d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'dd-provinsi' and @type = 'text' and @placeholder = 'Pilih Provinsi']</value>
      <webElementGuid>abbf286a-7123-47de-ae8b-f2aa7c92d358</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
