<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_MINTA PENAWARAN</name>
   <tag></tag>
   <elementGuidId>538279ff-90b4-45be-8f1e-3bd65fbb8043</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#offering</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='offering']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>b36ec51f-e964-4430-95c8-4f04e222676b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>relative flex whitespace-nowrap justify-center items-center px-4 gap-x-1.5 font-semibold bg-reliableBlack90  h-[52px] text-base leading-[22px] rounded    text-white w-full mt-6</value>
      <webElementGuid>33d436fa-becb-432c-bb05-811ff565e419</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>136d12bf-8fa4-45c9-a887-db56ca3cbf88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>offering</value>
      <webElementGuid>3456d37c-40fd-4235-940a-655bc1739b5a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>MINTA PENAWARAN</value>
      <webElementGuid>6c57b709-cbb9-4755-a037-12965d0d5c66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;splide15-slide01&quot;)/div[@class=&quot;px-4 lg:px-0 md:px-4 pb-4&quot;]/button[@id=&quot;offering&quot;]</value>
      <webElementGuid>d9e0d253-009b-43c1-80f0-4719aab58a25</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='offering']</value>
      <webElementGuid>85eecf33-544a-4e59-a5d0-2f00071f4c5e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='splide15-slide01']/div[3]/button</value>
      <webElementGuid>291925ac-d351-4e49-91f6-62f4790b6725</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/div[3]/button</value>
      <webElementGuid>988e8feb-253f-40ee-8665-c2cdcf3d7e45</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and @id = 'offering' and (text() = 'MINTA PENAWARAN' or . = 'MINTA PENAWARAN')]</value>
      <webElementGuid>a3d5b4ba-e6da-4892-9939-b7e79695763a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
