<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_MINTA PENAWARAN_splide__arrow splide__arrow--next</name>
   <tag></tag>
   <elementGuidId>d74c89fd-5c71-4c65-90f9-0b4e0c003d14</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.splide__arrow.splide__arrow--next</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>981afd1c-2dc8-4665-8b1c-0b36032e18e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>splide__arrow splide__arrow--next</value>
      <webElementGuid>23df175f-d08b-4233-84ff-90edb26e2323</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>182dacce-1beb-4673-abe4-b972fa7dd0a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Next slide</value>
      <webElementGuid>5690e6c8-339f-43f5-b401-5bcf07f99123</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>splide15-track</value>
      <webElementGuid>0f30fbfe-2250-4b7f-8534-93e86f62cd41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;splide15&quot;)/div[@class=&quot;splide__arrows splide__arrows--ltr&quot;]/button[@class=&quot;splide__arrow splide__arrow--next&quot;]</value>
      <webElementGuid>72c5e121-6aa1-4d00-b7ad-8a3393387724</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[2]</value>
      <webElementGuid>952b958c-902d-4157-98d7-37c9b2b6efe6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='splide15']/div[2]/button[2]</value>
      <webElementGuid>f52ca405-1162-4e69-a9f4-087dd253c9cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[2]</value>
      <webElementGuid>1b597fb1-35b5-4d24-8d66-3058f935cfda</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button']</value>
      <webElementGuid>d498c1fa-7746-4b49-8011-02a1bce80569</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
