<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Berikutnya</name>
   <tag></tag>
   <elementGuidId>1da6862e-443c-4f18-ae80-29833dd8df56</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;__next&quot;]/main/section[1]/div/div[2]/div[3]/nav/ul/li[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>6f95ab83-5993-444f-9c6c-5665c934bb27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hidden lg:inline-block</value>
      <webElementGuid>43e53ac3-214a-49e3-9fb9-a7fab699b789</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Berikutnya</value>
      <webElementGuid>7351dd90-5d9f-4ff1-abeb-98b548882c27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/main[@class=&quot;bg-white&quot;]/section[@class=&quot;my-[10px] lg:my-[20px]&quot;]/div[@class=&quot;lg:container xl:px-0&quot;]/div[@class=&quot;my-[9px] lg:my-2&quot;]/div[@class=&quot;flex items-center justify-center mt-6 lg:mt-9 lg:justify-between&quot;]/nav[@class=&quot;container w-full&quot;]/ul[@class=&quot;flex items-center justify-center gap-4 lg:justify-end lg:gap-3&quot;]/li[5]/a[@class=&quot;flex items-center p-2 text-sm text-reliableBlack border border-[#E9E9E9] rounded lg:border-transparent lg:p-0 lg:ml-1 false&quot;]/span[@class=&quot;hidden lg:inline-block&quot;]</value>
      <webElementGuid>c3f14b66-d9ce-4783-b199-e300d17f5073</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/main/section/div/div[2]/div[3]/nav/ul/li[5]/a/span</value>
      <webElementGuid>19ba5962-b125-4bb9-ae3d-6837186787a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[5]/a/span</value>
      <webElementGuid>ee2b11f7-ce37-432d-b587-bb0f51d2910d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Berikutnya' or . = 'Berikutnya')]</value>
      <webElementGuid>c42319e8-dbd5-4481-bd9c-b50b0dcef2e1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
