<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Field Email</name>
   <tag></tag>
   <elementGuidId>70a631f8-31bd-4586-819b-2813f11131f2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;email&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='email']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Input Company Email Address&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1a0d979a-2dfc-4f2a-ac47-cee43b9058ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>b32a2ae8-36e0-42f0-a8d7-73dc94674238</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>04b2d938-1f96-494f-a480-61ea6bfa4ebf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Input Company Email Address</value>
      <webElementGuid>6eddcd35-c65f-427a-8aea-8b4792c2c9b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-full px-3 h-[52px] flex items-center placeholder:text-[#DEDEDE] focus:outline-none rounded-md  false</value>
      <webElementGuid>62680893-4d35-4879-b279-2307b39fc730</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>max</name>
      <type>Main</type>
      <value>100</value>
      <webElementGuid>68f100ca-8b2a-498b-8299-8b7f5fe8646a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[2]/div[@class=&quot;flex justify-end md:justify-end items-center bg-cover bg-center global-bg&quot;]/div[@class=&quot;rounded-lg&quot;]/div[@class=&quot;bg-white p-10 rounded-lg w-[528px] mx-[73px] my-8 h-[650px] flex flex-col overflow-auto&quot;]/div[@class=&quot;flex-grow&quot;]/div[1]/form[1]/div[@class=&quot;flex flex-col gap-y-4&quot;]/div[1]/div[@class=&quot;relative w-full flex flex-col gap-1 w-full h-[75px] h-auto  text-[16px]&quot;]/div[@class=&quot;null border border-[#DEDEDE] rounded-md text-black bg-white&quot;]/input[@class=&quot;w-full px-3 h-[52px] flex items-center placeholder:text-[#DEDEDE] focus:outline-none rounded-md  false&quot;]</value>
      <webElementGuid>311d2ff2-03a0-49d5-8f20-cadb26049549</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='email']</value>
      <webElementGuid>1fe42ea0-b6e6-42fa-970a-f19bc5d9612d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div[2]/div/div/div/div[2]/div/form/div/div/div/div[2]/input</value>
      <webElementGuid>179f86c0-3bf8-43ec-96a6-29cd4e266518</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>06280b6b-4f79-4602-b9bc-9b890e481c3e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'email' and @name = 'email' and @placeholder = 'Input Company Email Address']</value>
      <webElementGuid>3a22d592-c302-41e1-8b69-d5f5946c303d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
