<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Button Simulasi Kredit</name>
   <tag></tag>
   <elementGuidId>d75222d3-a9f2-4a83-81bd-6dae1d03f466</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#id-simulasi-kredit</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='id-simulasi-kredit']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>c674ebed-c136-437f-a03c-35234936d9dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>id-simulasi-kredit</value>
      <webElementGuid>692a2ac3-212b-4f87-aab4-419953b5e0c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>relative flex whitespace-nowrap justify-center items-center px-4 gap-x-1.5 font-semibold bg-reliableBlack5  h-[52px] text-base leading-[22px] rounded    !text-[14px] w-1/3 text-black  lg:block hidden</value>
      <webElementGuid>e101ab71-17e6-41ce-a91d-4d1e4ffdca88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>b1d138da-89d2-4511-9814-774dc2bc714f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>SIMULASI KREDIT</value>
      <webElementGuid>f6fd74f2-7f15-406d-be1b-ee2c041a376f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;id-simulasi-kredit&quot;)</value>
      <webElementGuid>fb52d287-34d2-4b36-aa43-7415333806a9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='id-simulasi-kredit']</value>
      <webElementGuid>a0969d23-8ace-45c9-a801-02586b8e7aa7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/main/section[2]/div/div[3]/div[2]/div[2]/div/button</value>
      <webElementGuid>2f87a316-d9c4-4d82-bf72-e2537ccb73fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='UNDUH KATALOG'])[1]/following::button[1]</value>
      <webElementGuid>f5dfcf2b-d162-4637-9d68-171681d4f6ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pilih'])[1]/following::button[1]</value>
      <webElementGuid>26cc531c-c415-434e-aade-3bebb619607a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PRE ORDER'])[1]/preceding::button[1]</value>
      <webElementGuid>1ba0852c-053f-4e48-a98f-d43ff3089e0e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/button</value>
      <webElementGuid>f9ae0f2e-e415-4fc8-84f7-fe3d02b95e80</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'id-simulasi-kredit' and @type = 'submit' and (text() = 'SIMULASI KREDIT' or . = 'SIMULASI KREDIT')]</value>
      <webElementGuid>ece76b19-bb04-4f4b-b6df-d815e969f18f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
