<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Button Hitung Simulasi</name>
   <tag></tag>
   <elementGuidId>013db3fd-99d2-4dc7-911c-0043a1cb883f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#id-hitung-simulasi</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='id-hitung-simulasi']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>c55c2147-ce1c-4cd7-9fa3-a943efd57398</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>id-hitung-simulasi</value>
      <webElementGuid>7930e335-8815-4303-91ba-186dd2f3cd7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>relative flex whitespace-nowrap justify-center items-center px-4 gap-x-1.5 font-semibold bg-reliableBlack  h-[52px] text-base leading-[22px] rounded    text-white w-full lg:w-[328px] my-6 lg:my-0</value>
      <webElementGuid>5732c15e-986f-40f4-833c-129a7cf880a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>f39f2cf3-a2d0-43de-8151-f6633a98e115</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>HITUNG SIMULASI</value>
      <webElementGuid>72c090f7-3b23-43d4-b10f-c15d22cd2f9e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;id-hitung-simulasi&quot;)</value>
      <webElementGuid>fcab0443-ea96-472c-92ac-ca010cfe6d13</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='id-hitung-simulasi']</value>
      <webElementGuid>5e4cf3f3-8f7c-4cd4-aba7-f0d8743579f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/main/div[2]/div/div[2]/section[2]/div/button</value>
      <webElementGuid>af9afab3-f5c1-4b09-a062-b43770aa007d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='MINTA PENAWARAN'])[1]/following::button[6]</value>
      <webElementGuid>cf623f25-d058-4fdb-945f-bc4148ab0a07</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pilih'])[2]/following::button[6]</value>
      <webElementGuid>af904bf5-ed04-4f05-9bf0-8d02a3b73f2e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lihat Selengkapnya'])[1]/preceding::button[1]</value>
      <webElementGuid>aa4152eb-c171-4cad-928e-93cf56188f02</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section[2]/div/button</value>
      <webElementGuid>ef7c76c5-12c5-4852-bfec-eda6f1b1274d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'id-hitung-simulasi' and @type = 'submit' and (text() = 'HITUNG SIMULASI' or . = 'HITUNG SIMULASI')]</value>
      <webElementGuid>d2842f77-44fb-466a-a71a-caac923678c5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
