<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Presentasi Uang Muka</name>
   <tag></tag>
   <elementGuidId>c55ef8ba-a48c-483f-a75b-59eca3d883b6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@class='rc-slider-dot'][contains(@style, 'left: 90%')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>315d576e-7d4b-4c3c-8333-4449bff45087</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rc-slider-dot</value>
      <webElementGuid>1ec0b6b9-1a1e-4617-b670-413e83a9b075</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/main[@class=&quot;bg-white&quot;]/div[@class=&quot;opacity-100 duration-300 ease-in-out fixed w-[100vw] h-[100vh] z-[70] top-1/2 left-1/2 transform -translate-x-1/2 -translate-y-1/2 bg-opacity-30 bg-black !z-[100]&quot;]/div[@class=&quot;lg:max-h-[80vh] false duration-300 ease-in-out flex flex-col absolute bg-white rounded top-1/2 left-1/2 transform -translate-x-1/2 -translate-y-1/2 !h-[95vh] w-[90vw] md:!w-[622px]&quot;]/div[@class=&quot;overflow-auto bg-gray10 p-6&quot;]/section[@class=&quot;container text-black lg:px-10 lg:py-5 lg:flex lg:flex-col  lg:gap-10 lg:items-center mt-4&quot;]/div[@class=&quot;lg:flex lg:flex-col lg:flex-1 lg:gap-12 lg:items-center  lg:px-16&quot;]/div[@class=&quot;mt-6 lg:mt-0 w-full&quot;]/div[@class=&quot;h-20 lg:h-28 pt-14 lg:pt-20 w-full px-7 lg:px-0&quot;]/div[@class=&quot;rc-slider slider-custom-simulation-modal rc-slider-horizontal rc-slider-with-marks&quot;]/div[@class=&quot;rc-slider-step&quot;]/span[@class=&quot;rc-slider-dot&quot;]</value>
      <webElementGuid>43619fbd-a163-4ee6-93b2-6456df81eff1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/main/div[2]/div/div[2]/section[2]/div/div/div/div/div[3]/span[10]</value>
      <webElementGuid>c33ef4b1-7eb9-487f-bd1d-25edfb5b0253</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[10]</value>
      <webElementGuid>939df59c-7691-4113-813a-fe8733dc2772</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
