<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Change File_Kop_surat</name>
   <tag></tag>
   <elementGuidId>1cbcce38-8cbe-4716-9939-6bd6b03abf9b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='layout-content']/div[2]/div[8]/div[2]/div/div/div/div/label</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>014ebb79-589e-41f6-9051-ce67e56220b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>upload-change-file-Kop Surat</value>
      <webElementGuid>76073d28-ed63-4f1a-b782-5927d8e7c502</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>min-w-max cursor-pointer text-[12px] leading-[14px] text-secondary10 underline</value>
      <webElementGuid>6102d21b-2d98-4a95-b69e-65847b45f2aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>upload-action-label</value>
      <webElementGuid>d546ff4b-4b1c-4fcc-8904-6edfc289a880</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Change File</value>
      <webElementGuid>5b908adb-dfaf-4df0-87f7-f1f60c5930b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;layout-content&quot;)/div[@class=&quot;relative grid grid-cols-2 gap-x-6 gap-y-4 px-10&quot;]/div[@class=&quot;flex flex-col gap-1&quot;]/div[@class=&quot;flex items-center justify-between rounded-md border-2 px-6 py-[21px] border-[#b7b7b7] gap-x-2 border-dashed&quot;]/div[@class=&quot;flex gap-x-4&quot;]/div[@class=&quot;flex flex-col gap-y-[2px]&quot;]/div[@class=&quot;flex gap-x-2 break-all&quot;]/div[@class=&quot;flex items-center&quot;]/label[@class=&quot;min-w-max cursor-pointer text-[12px] leading-[14px] text-secondary10 underline&quot;]</value>
      <webElementGuid>69e6e0d2-e674-461e-bfa8-b794c5920963</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='layout-content']/div[2]/div[8]/div[2]/div/div/div/div/label</value>
      <webElementGuid>19ca436b-3b69-44e0-aa41-684b3fa02b8b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lihat'])[1]/following::label[1]</value>
      <webElementGuid>d2f6dc4c-956c-412a-99f5-3f59930b387b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Change File'])[1]/following::label[1]</value>
      <webElementGuid>bb7d6721-b05a-4cca-8ce4-5892c3c568f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lihat'])[2]/preceding::label[1]</value>
      <webElementGuid>99fde1f4-10b2-46bb-93cf-bd33921f5e42</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Batal'])[1]/preceding::label[1]</value>
      <webElementGuid>310baf8e-b0d9-44a7-bfb5-59630f9652d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div[2]/div/div/div/div/label</value>
      <webElementGuid>cf2ae02b-f7e9-447e-8cce-3dbcddf16189</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = 'Change File' or . = 'Change File')]</value>
      <webElementGuid>f3126464-5ac5-4948-b777-6989091b546f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
