<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button Login</name>
   <tag></tag>
   <elementGuidId>3bfde4eb-d7bf-49e0-a908-3cf57663480c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.text-center.flex</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/form/div/div/div[3]/button/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;LOGIN&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>742a5d80-9c2d-4832-9c24-25df9ac2ddbd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-center flex </value>
      <webElementGuid>c8083c3e-617e-467c-8593-fee4d6dc1edd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>LOGIN</value>
      <webElementGuid>a9aa9e98-bf63-44df-b3b1-f23a44ce8523</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/form[@class=&quot;bg-[url('https://astradigitaldigiroomstg.blob.core.windows.net/storage-general-001/bg-login.png')] bg-cover&quot;]/div[@class=&quot;flex justify-center items-center min-h-screen mx-6&quot;]/div[@class=&quot;bg-white shadow-md border rounded-lg p-5 md:p-8 mb-4 w-full md:w-1/3&quot;]/div[@class=&quot;flex items-center justify-between&quot;]/button[@class=&quot;relative flex whitespace-nowrap justify-center items-center px-4 gap-x-1.5 font-semibold bg-supportiveRed  h-[52px] text-base leading-[22px] rounded    w-1/2 text-white&quot;]/div[@class=&quot;text-center flex&quot;]</value>
      <webElementGuid>b8e9bcda-b8e9-4d6a-9e12-617c87b18280</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/form/div/div/div[3]/button/div</value>
      <webElementGuid>bdb82859-bb47-46b7-be14-13eb166bcdf3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Password'])[1]/following::div[4]</value>
      <webElementGuid>ea05ce68-0dba-4910-a608-547ee1799191</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Username'])[1]/following::div[8]</value>
      <webElementGuid>6a202616-7bee-49b2-896c-186763ff81be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='LOGIN']/parent::*</value>
      <webElementGuid>f016ae0a-f5c3-4bc4-8789-08003a8f3f6f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button/div</value>
      <webElementGuid>0aa6c7c9-1665-44c1-8a79-22aa31214741</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'LOGIN' or . = 'LOGIN')]</value>
      <webElementGuid>1942b373-7d4d-4a1f-b53f-99d2db27626b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
