<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Konfirmasi Password_confirmNewPassword</name>
   <tag></tag>
   <elementGuidId>145fe3d8-c806-4e17-a98b-c139d0341f5f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#confirmNewPassword</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='confirmNewPassword']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Konfirmasi Password Baru&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>56bb6919-77ca-4292-b6a7-495251c89aeb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>confirmNewPassword</value>
      <webElementGuid>8a1fc37c-6050-41d8-9bcc-cb753d42de27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>60bbaa78-5256-4655-a626-c226ca926038</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Konfirmasi Password Baru</value>
      <webElementGuid>e81276c8-ed15-4d7c-9156-909697e46e42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>bg-gray-100 border-[#5F5F5F] max-h-fit lg:max-h-fit focus:border-reliableBlack border-0 border-b px-5 py-4 focus:ring-0</value>
      <webElementGuid>f2fd04ca-fd5e-42a6-bbd8-82a8d6b2dd84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;confirmNewPassword&quot;)</value>
      <webElementGuid>b431af9c-c769-46a8-9982-dd62995b937d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='confirmNewPassword']</value>
      <webElementGuid>fb136104-a54e-4d08-8cf6-fd537d858131</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id=':r2:']/div/form/div/div/div[2]/input</value>
      <webElementGuid>ef7ab02d-10e2-4239-a572-2a6aae807779</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>41e59f16-acc0-4178-81b6-09cc596db5b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'confirmNewPassword' and @type = 'password' and @placeholder = 'Konfirmasi Password Baru']</value>
      <webElementGuid>cb880df2-78b9-4212-9c76-4f53c09731cc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
