<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Button Pre Order</name>
   <tag></tag>
   <elementGuidId>2223a80d-f28f-4984-a9c6-5986f91a6471</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#id-beli-mobil</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='id-beli-mobil']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>4245c0d1-4d79-4aa0-aaec-4a893ce35954</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>id-beli-mobil</value>
      <webElementGuid>c83a90b4-9fd1-45ad-bdf7-192d9734dadf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>relative flex whitespace-nowrap justify-center items-center px-4 gap-x-1.5 font-semibold bg-supportiveRed  h-[52px] text-base leading-[22px] rounded    text-white !bg-reliableBlack md:px-0 px-4 w-full !text-[14px] btn-primary-white bookbtn btn-bookOrBuy btn-book-buy-new-pdp</value>
      <webElementGuid>7a51e486-aea0-493b-8055-0eef34b67e12</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>fed805d2-3bec-449c-9cc3-d8bb48f9caf8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>PRE ORDER</value>
      <webElementGuid>0a76d15d-6c97-4fe1-b00f-d6ef7386f5a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;id-beli-mobil&quot;)</value>
      <webElementGuid>d417bf6b-3088-45f2-aee7-87b8292b9058</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='id-beli-mobil']</value>
      <webElementGuid>f56b8607-5ec4-4803-a5ca-4b1efa01eadb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/main/section[2]/div/div[3]/div[2]/div[2]/div/a/button</value>
      <webElementGuid>42eb5c37-c606-491d-9d8a-3ffe89aa4954</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SIMULASI KREDIT'])[1]/following::button[1]</value>
      <webElementGuid>a4d6091c-a946-47e1-b57a-bd29cb7973e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='UNDUH KATALOG'])[1]/following::button[2]</value>
      <webElementGuid>e8ac4367-1181-4a10-b3d9-ab76c63b16fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SIMULASI KREDIT'])[2]/preceding::button[1]</value>
      <webElementGuid>83c46bf3-9266-46a5-88cc-e29212eae2a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/button</value>
      <webElementGuid>b2f5da5d-f0d6-4c52-8829-6d4865b723ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'id-beli-mobil' and @type = 'submit' and (text() = 'PRE ORDER' or . = 'PRE ORDER')]</value>
      <webElementGuid>ab4b9ce5-0d4c-42ec-9900-78cf8fe31826</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
