<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Nav Bar Interior</name>
   <tag></tag>
   <elementGuidId>2a8d0733-da7e-4c85-ac0a-8c85b2cc020f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#id-ncp-interior</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='id-ncp-interior']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>fc6ff329-2897-4fba-893b-49cbea6dcf1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>id-ncp-interior</value>
      <webElementGuid>4a6f6d29-102f-48d6-a405-12feb7d943cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>flex items-center text-xs uppercase text-reliableBlack whitespace-nowrap py-3.5 px-4 border-b-4 lg:text-base lg:py-4 lg:px-5 lg:border-b-[3px] hover:border-supportiveRed border-transparent</value>
      <webElementGuid>d1126aa4-3249-4701-820d-f90d077a3475</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>INTERIOR</value>
      <webElementGuid>1a946e05-e841-4bc5-83ca-3256cda03b53</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;id-ncp-interior&quot;)</value>
      <webElementGuid>a479164d-ec77-44f4-b876-e3cfc0ba6aff</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='id-ncp-interior']</value>
      <webElementGuid>96492c5d-3bdd-40e7-881b-980e3fbe02dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/main/section/div/ul/li[3]/div/a/div</value>
      <webElementGuid>aa4f1379-04d4-4b19-8188-a26e9a78edca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SPESIFIKASI'])[1]/following::div[2]</value>
      <webElementGuid>ec23fbf7-102a-4478-81df-3fb59b52cda1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='OVERVIEW'])[2]/following::div[4]</value>
      <webElementGuid>5941fabc-6338-4f63-90b8-2c2ffcc6203f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='EKSTERIOR'])[1]/preceding::div[1]</value>
      <webElementGuid>20b9ef03-236d-42e1-a3cf-6828502de4e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]/div/a/div</value>
      <webElementGuid>7558e6d2-b4b7-481e-ac9b-3140cc1175ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'id-ncp-interior' and (text() = 'INTERIOR' or . = 'INTERIOR')]</value>
      <webElementGuid>c3ada897-b11c-40bd-bc21-ad69c030968b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
