<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Input Range Harga</name>
   <tag></tag>
   <elementGuidId>d528a3bc-33ed-49d8-8d05-d72ecb85f666</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input.range-min.absolute.w-full.-top-1.h-1.bg-transparent.appearance-none.pointer-events-none</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[contains(@value, '331171300')]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@value = '${valueMin}']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>478d5b2c-5303-49d0-8cce-4def7951e36d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>range</value>
      <webElementGuid>4641f371-2bec-456f-92e0-16d3b6f785c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>min</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>128391d0-ca99-4ab8-a899-c125b5a1573f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>step</name>
      <type>Main</type>
      <value>100</value>
      <webElementGuid>437c2f09-971d-403d-ad1f-6e7d9616c28a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>max</name>
      <type>Main</type>
      <value>2141250000</value>
      <webElementGuid>c5d8e2ed-d9a3-4236-b9bc-709a3e4685ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>range-min absolute w-full -top-1 h-1 bg-transparent appearance-none pointer-events-none</value>
      <webElementGuid>c289946c-09b0-410e-b74d-2372b9a02621</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>slider-min</value>
      <webElementGuid>dc05dfe1-1d54-4bd9-9a77-97c2fa2b76a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>${valueMin}</value>
      <webElementGuid>8c14f4a5-0a45-49ff-a066-221a6fa2c093</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/main[@class=&quot;bg-white&quot;]/div[@class=&quot;md:container md:px-0&quot;]/div[@class=&quot;lg:flex lg:gap-6&quot;]/section[@class=&quot;mt-4 mb-6 lg:my-8 w-full max-w-[292px]&quot;]/div[@class=&quot;border-r border-[#E9E9E9] pr-4 md:block hidden&quot;]/div[@class=&quot;mb-3&quot;]/div[@class=&quot;text-reliableBlack&quot;]/button[@id=&quot;newCar&quot;]/details[@class=&quot;py-[18px] lg:px-0&quot;]/div[@class=&quot;text-start text-sm font-normal text-reliableBlack leading-relaxed lg:text-base lg:leading-relaxed px-4 lg:px-0&quot;]/div[1]/div[@class=&quot;flex flex-col w-full rounded-lg py-4&quot;]/div[@class=&quot;mb-4&quot;]/div[@class=&quot;range-input relative&quot;]/input[@class=&quot;range-min absolute w-full -top-1 h-1 bg-transparent appearance-none pointer-events-none&quot;]</value>
      <webElementGuid>a4f83b82-1dbf-49a0-8894-ae98e75c0cc6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='0']</value>
      <webElementGuid>71bda2b8-a932-4ac0-b320-ff63af4300a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='newCar']/details/div/div/div/div[2]/div[2]/input</value>
      <webElementGuid>4be18ca8-2de5-4f32-b9ff-682a05b6abf7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>0140189b-d8d9-49e4-b963-431da626fd8d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'range']</value>
      <webElementGuid>0dfd0538-bfe4-49a4-bc9a-e7e7e037c2ac</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
