<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Model Mobil_dd-model-mobil</name>
   <tag></tag>
   <elementGuidId>e09808e0-6217-4187-b31e-0c6cc116d974</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[contains(@id, 'dd-model-mobil')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#dd-model-mobil</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2c7e14f0-e420-416c-9fe2-4e87faad66a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dd-model-mobil</value>
      <webElementGuid>7eaabe28-54dc-4940-bbd8-3a842c6a3a8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>45cdcc5d-2f34-4de8-8861-89d06bdf310e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-full outline-none px-4 py-2 bg-reliableBlack3 placeholder:text-reliableBlack60 text-reliableBlack border-b border-reliableBlack30 focus:border-reliableBlack60 lg:px-5 lg:py-4 !bg-white border-[#5F5F5F] max-h-fit lg:max-h-fit focus:border-reliableBlack false cursor-pointer</value>
      <webElementGuid>91e7da2a-36d6-41f0-b763-d2cbfa51b693</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Pilih Mobil</value>
      <webElementGuid>6b339267-4015-4fec-a47c-1aa16d6632bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dd-model-mobil&quot;)</value>
      <webElementGuid>f804e120-1880-427b-bb1e-593a9dcc4074</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='dd-model-mobil']</value>
      <webElementGuid>e2896ad2-1a18-499c-b73e-a4edc9c307b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/main/div[2]/div/div/div[2]/div/section/form/div[2]/div/div/input</value>
      <webElementGuid>4ce56f70-af0c-4af4-8d4b-692e7f326d48</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/input</value>
      <webElementGuid>9b619025-f233-4ba3-8aeb-f406a7cbeb61</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'dd-model-mobil' and @type = 'text' and @placeholder = 'Pilih Mobil']</value>
      <webElementGuid>e2f5096a-6849-4ffa-bb43-fccebea05871</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
