<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Halaman 2</name>
   <tag></tag>
   <elementGuidId>f2e8bced-e991-4390-b546-515bf83499ae</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//a[contains(@class, 'py-2 px-4 text-sm font-normal text-reliableBlack border border-') and contains(@class, 'rounded lg:border-transparent') and @role='link'])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;2&quot;s]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>4629e715-45b5-4b3d-a588-1758abe3ef42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>py-2 px-4 text-sm font-normal text-reliableBlack border border-[#E9E9E9] rounded lg:border-transparent false</value>
      <webElementGuid>f27d12d5-2d88-4994-a018-d2b7f0ed22fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>link</value>
      <webElementGuid>7181f3bd-20c2-4eaf-ab2d-e73439854a1e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://uat.auto2000.co.id/promosi?page=2</value>
      <webElementGuid>36dcc9d5-6315-42b7-9645-a197eb0207bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>30551ab8-3a25-4471-8220-b2e2205ecb1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/main[@class=&quot;bg-white&quot;]/div[1]/section[@class=&quot;mt-4 mb-6 lg:my-8&quot;]/div[@class=&quot;lg:container xl:px-0&quot;]/div[@class=&quot;flex items-center justify-center mt-6 lg:mt-9 lg:justify-between&quot;]/nav[@class=&quot;container w-full&quot;]/ul[@class=&quot;flex items-center justify-center gap-4 lg:justify-end lg:gap-3&quot;]/li[3]/a[@class=&quot;py-2 px-4 text-sm font-normal text-reliableBlack border border-[#E9E9E9] rounded lg:border-transparent false&quot;]</value>
      <webElementGuid>77b88bf2-824f-4214-8cd9-63bfe074ea3d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/main/div/section/div/div[3]/nav/ul/li[3]/a</value>
      <webElementGuid>9f66a542-2edc-4573-905d-1c35d478abc3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'2')]</value>
      <webElementGuid>0a1526af-a78f-4463-98d9-e7059ab995f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sebelumnya'])[1]/following::a[2]</value>
      <webElementGuid>480a2d2c-8b77-44fc-8072-3aa4722a854d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='dari'])[1]/following::a[3]</value>
      <webElementGuid>b71dde62-fb81-4b10-b335-2222736e2f6d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Berikutnya'])[1]/preceding::a[1]</value>
      <webElementGuid>a30ed036-0c31-4696-80e7-4a8a6f5fde37</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='INFORMASI PROMO TOYOTA'])[1]/preceding::a[2]</value>
      <webElementGuid>d8a15908-8bd8-4a82-881c-a6b0b530a74e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='2']/parent::*</value>
      <webElementGuid>a3573b43-1268-46e9-9073-163e212b5ed9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://uat.auto2000.co.id/promosi?page=2')]</value>
      <webElementGuid>0ddff891-bf55-420e-975e-c98ca05594ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]/a</value>
      <webElementGuid>17516590-3041-436b-b975-d12f3de6a139</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://uat.auto2000.co.id/promosi?page=2' and (text() = '2' or . = '2')]</value>
      <webElementGuid>b44c052d-d028-4957-91b1-e8887da5a872</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
