<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Model Mobil AE</name>
   <tag></tag>
   <elementGuidId>918b74ca-881f-4e9d-a6c9-376213c93bd1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='branch-dd-selected-car']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#branch-dd-selected-car</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>29514a90-0b36-491f-98a5-652bcd9223c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>branch-dd-selected-car</value>
      <webElementGuid>c6b8d26f-41a5-4b40-9190-725005c60922</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>fb98ae2f-ab9e-4f3e-bda6-754a5f8b6a6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-full outline-none px-4 py-2 bg-reliableBlack3 placeholder:text-reliableBlack60 text-reliableBlack border-b border-reliableBlack30 focus:border-reliableBlack60 lg:px-5 lg:py-4 px-5 py-3.5 bg-reliableBlack3 border-[#5F5F5F] max-h-fit lg:max-h-fit focus:border-reliableBlack cursor-pointer</value>
      <webElementGuid>61526984-258b-4c37-a911-4b320b02b32c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Pilih Mobil</value>
      <webElementGuid>06b35834-802f-4412-bc24-92660c7ddb23</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;branch-dd-selected-car&quot;)</value>
      <webElementGuid>1cc22a9e-add4-4ea9-8ae2-07f34c2074a4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='branch-dd-selected-car']</value>
      <webElementGuid>b7181c1c-b0a2-47c7-b817-65f4b3ec2a3a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/main/div[2]/div[2]/div/div[2]/div/form/div/div[3]/div/div/input</value>
      <webElementGuid>ee4d303a-0736-4b25-83c2-1903d3a731b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/form/div/div[3]/div/div/input</value>
      <webElementGuid>1f076c82-a7a7-4b8d-8013-cb8780c2d96b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'branch-dd-selected-car' and @type = 'text' and @placeholder = 'Pilih Mobil']</value>
      <webElementGuid>ab630cc1-86fe-47bb-a306-84b62631ae82</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
