<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Button Booking Servis</name>
   <tag></tag>
   <elementGuidId>2cb23223-dda5-4c6f-b4c1-cad35270dd1e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#branch-booking</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[contains(@class, 'relative') and contains(@class, 'flex') and contains(@class, 'whitespace-nowrap') and contains(@class, 'justify-center') and contains(@class, 'items-center') and contains(@class, 'px-4') and contains(@class, 'gap-x-1.5') and contains(@class, 'font-semibold') and contains(@class, 'bg-reliableBlack3') and contains(@class, 'lg:w-[185px]') and contains(@class, 'h-[52px]') and contains(@class, 'text-base') and contains(@class, 'leading-[22px]') and contains(@class, 'rounded')])[4]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;branch-booking&quot;)[count(. | //button[@class = 'relative flex whitespace-nowrap justify-center items-center px-4 gap-x-1.5 font-semibold bg-reliableBlack3 lg:w-[185px]  h-[52px] text-base leading-[22px] rounded    ' and @type = 'submit' and @aria-label = 'booking service button' and @id = 'branch-booking' and (text() = 'Booking Service' or . = 'Booking Service')]) = count(//button[@class = 'relative flex whitespace-nowrap justify-center items-center px-4 gap-x-1.5 font-semibold bg-reliableBlack3 lg:w-[185px]  h-[52px] text-base leading-[22px] rounded    ' and @type = 'submit' and @aria-label = 'booking service button' and @id = 'branch-booking' and (text() = 'Booking Service' or . = 'Booking Service')])]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>dc00d394-4539-48fe-8c4e-992759a878fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>relative flex whitespace-nowrap justify-center items-center px-4 gap-x-1.5 font-semibold bg-reliableBlack3 lg:w-[185px]  h-[52px] text-base leading-[22px] rounded    </value>
      <webElementGuid>c74d0e00-2588-41d6-9f2a-e0c813a47358</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>ea8bb5f8-3a59-4fd7-b05d-8d9582bcacd3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>booking service button</value>
      <webElementGuid>ba44c024-2e4a-4225-bec8-761eb0c0b3c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>branch-booking</value>
      <webElementGuid>fb82ec2b-3ec8-4190-b28d-5749835c60f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Booking Service</value>
      <webElementGuid>96d4da6e-d8bf-424e-bfea-b625b122ab25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;branch-booking&quot;)</value>
      <webElementGuid>8437f3ab-2614-48a0-9135-59ea6dface30</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='branch-booking']</value>
      <webElementGuid>5c05af16-5cda-4718-8f72-6105a604bc2f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/main/div/div/div/div/div[2]/a[2]/button</value>
      <webElementGuid>6a910a10-7c61-4d51-b09a-fe1206a99701</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hubungi Kami'])[2]/following::button[1]</value>
      <webElementGuid>67ac7414-597a-4c31-9b25-3a4d55400651</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Auto2000 Cempaka Putih'])[1]/following::button[2]</value>
      <webElementGuid>e3295fb7-ad6c-4f9d-bbeb-2675dc9831dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Minta Penawaran'])[1]/preceding::button[1]</value>
      <webElementGuid>e4b54a21-50dd-4563-a40d-fa9e17d17ade</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[2]/button</value>
      <webElementGuid>728a3416-dc0a-4a42-84c9-ebe36db9f026</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and @id = 'branch-booking' and (text() = 'Booking Service' or . = 'Booking Service')]</value>
      <webElementGuid>dc1aa3d2-bb49-49a0-bccf-76475bac9f8c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
