<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Field Nama</name>
   <tag></tag>
   <elementGuidId>04a33f18-f42f-4ec1-9e2e-cb6516de9408</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='branch-input-fullname']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#branch-input-fullname</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d4936a1b-c187-4025-a0f5-ea4048eb89e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>branch-input-fullname</value>
      <webElementGuid>39f7b72b-302e-4862-84fd-6839f0a366a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Nama Depan dan Belakang</value>
      <webElementGuid>a12cd233-fc17-4306-9457-e692637b394d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>69b48d9e-8b25-4aa3-a9d3-995233fadc97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-full outline-none bg-reliableBlack3 bg-reliableBlack3 text-reliableBlack border-b border-reliableBlack30 placeholder:text-reliableBlack60 focus:border-reliableBlack60 false w-full px-4 py-2 lg:px-5 lg:py-4 max-h-[30px] lg:max-h-[40px] text-base lg:text-base leading-4 px-5 py-3.5 bg-reliableBlack3 border-[#5F5F5F] max-h-fit lg:max-h-fit focus:border-reliableBlack null  focus:outline-none</value>
      <webElementGuid>12472002-1615-49ba-a804-3ac688da843f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;branch-input-fullname&quot;)</value>
      <webElementGuid>3365bcbc-986e-46c9-bf5b-a894bf2a1412</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='branch-input-fullname']</value>
      <webElementGuid>bba888ab-bba5-4591-b337-2856b5c40d0b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//div[@id='branch-input-fullname-plp ']/div/div/div/input)[2]</value>
      <webElementGuid>8e2f5372-6808-4449-bcd8-5bff18c29f2a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/form/div/div/div/div/div/input</value>
      <webElementGuid>b6ccdcbf-6cec-46d2-953e-5f0324883e06</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'branch-input-fullname' and @placeholder = 'Nama Depan dan Belakang' and @type = 'text']</value>
      <webElementGuid>f86cbda6-a9ff-4faf-8d6d-34822a0de049</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
