<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Button Simulasi Kredit</name>
   <tag></tag>
   <elementGuidId>3b7cfd58-71ab-4ed5-885d-9e95ffd57308</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='id-simulasi-kredit']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#id-simulasi-kredit</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>3e2c3455-44da-4a3b-be2e-aea249e77b57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>id-simulasi-kredit</value>
      <webElementGuid>3a73dcf3-2c71-4753-a009-685556b90e9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>relative flex whitespace-nowrap justify-center items-center px-4 gap-x-1.5 font-semibold bg-reliableBlack5 !text-[14px]  h-[52px] text-base leading-[22px] rounded    w-full mt-5</value>
      <webElementGuid>d58ab664-0e87-45c2-86a7-da127deafb8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>9814118a-77c6-43dc-bda7-015acc0ce00f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>SIMULASI KREDIT</value>
      <webElementGuid>00f7bf6f-f970-4c51-bbd6-80a331b929eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;id-simulasi-kredit&quot;)</value>
      <webElementGuid>5e57c556-0269-4a5e-8fb6-badba1d49ac7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='id-simulasi-kredit']</value>
      <webElementGuid>50cde0c2-b592-4c37-bdb3-d9d1eb50d18f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/main/section[2]/div/div[3]/div[4]/div[4]/button</value>
      <webElementGuid>2fea2632-28cc-42d6-9c12-10aa17f3f107</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='BELI MOBIL'])[1]/following::button[1]</value>
      <webElementGuid>d91a46f6-5159-47a7-9835-a8ea500bbd30</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dapatkan informasi AGYA lengkap mulai dari harga OTR, Spesifikasi dan Promo'])[1]/following::button[2]</value>
      <webElementGuid>aaf1ea22-56c4-4647-bd2c-19d528f30a2f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='TOYOTA AGYA 2024'])[2]/preceding::button[1]</value>
      <webElementGuid>b14412fd-b1dd-4770-82a1-2f3541c37354</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[4]/button</value>
      <webElementGuid>1091e08e-4d04-4b83-8e97-bed4f81c0c4d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'id-simulasi-kredit' and @type = 'submit' and (text() = 'SIMULASI KREDIT' or . = 'SIMULASI KREDIT')]</value>
      <webElementGuid>a0651548-cf99-4233-afe3-6037858ccad0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
