<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Button Pilih</name>
   <tag></tag>
   <elementGuidId>a9ce6c28-9aed-4ff9-969f-b7cea5003789</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='id-pilih-variant']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#id-pilih-variant</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>97b66f81-148c-450d-805d-a56282eb9346</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>flex justify-end items-center p-3 gap-x-3 text-base font-bold md:p-4 md:justify-center md:flex-1 md:rounded     bg-supportiveRed text-white text-center w-full mt-[50px] md:mt-8 p-5 md:p-4</value>
      <webElementGuid>f90e55cc-ac56-4ae4-be9f-417837574177</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>id-pilih-variant</value>
      <webElementGuid>3353b14f-a2a0-4286-ba2c-048977c0855e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>variant</name>
      <type>Main</type>
      <value>bg-supportiveRed</value>
      <webElementGuid>06f2a019-f2b0-4422-a234-88bddb910b8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Pilih</value>
      <webElementGuid>f9342eea-2148-4537-bb25-73785f986055</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;id-pilih-variant&quot;)</value>
      <webElementGuid>42553a01-b934-4944-8e92-7b33643b9760</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='id-pilih-variant']</value>
      <webElementGuid>7674df6a-193e-4dd3-a096-6144384eddcd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/main/section[2]/div/div[2]/div/div[2]/div/section/div[2]/button</value>
      <webElementGuid>1e1ddae5-7f19-4621-bd37-c394bbe2663b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='HUBUNGI ACCOUNT EXECUTIVE KAMI'])[1]/following::button[1]</value>
      <webElementGuid>77d6d2b2-26fc-468c-8d60-91a3800551cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bingung memilih tipe yang sesuai?'])[1]/following::button[1]</value>
      <webElementGuid>fcae652c-2acc-4e4e-87d6-298df10e6bcd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='AUTO2000 ©'])[1]/preceding::button[1]</value>
      <webElementGuid>c6993ea1-91b4-4287-8063-30c44d237f33</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section/div[2]/button</value>
      <webElementGuid>cbf19373-4a0f-4da9-88ab-5c7d87c7d2be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'id-pilih-variant' and (text() = 'Pilih' or . = 'Pilih')]</value>
      <webElementGuid>715fefba-ebcc-4b15-b1a0-e981e6b587d3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
