<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Otomatis 1</name>
   <tag></tag>
   <elementGuidId>770c462a-d792-403d-b0c4-11d56320cffa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#radio-0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='radio-MATIC-0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>714dbf75-6a79-4520-af69-7239ebb9c406</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>radio-0</value>
      <webElementGuid>fe219aa1-5100-4d55-9188-8adec30580d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>9cea2fdc-f1d9-4cd6-87a1-a57fb4e20619</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>radio-options</value>
      <webElementGuid>6ed86738-3fb4-429d-a533-6b0d40ccbe85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-4 h-4 text-[#231F20] bg-gray-100 md:mt-0  mt-2 focus:ring-[#4F4C4D]</value>
      <webElementGuid>cece3a69-de15-4ad1-8972-c4888db123e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>B101GA/T02_T1E7</value>
      <webElementGuid>fb41bd08-5784-432c-a41e-0ecdcc730895</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;radio-0&quot;)</value>
      <webElementGuid>99627abf-db09-4450-9d8c-3f2258e97297</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='radio-0']</value>
      <webElementGuid>f798aa06-b2bd-48fd-bf9e-55d44d6b9b5a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/main/section[2]/div/div[2]/div/div[2]/div/section/div/div[2]/ul/li/div/input</value>
      <webElementGuid>903af4c0-95df-4ecf-936d-063444ee522c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/div/input</value>
      <webElementGuid>5aa45e06-528a-4057-9cd6-ecd90a732bf0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'radio-0' and @type = 'radio' and @name = 'radio-options']</value>
      <webElementGuid>daa93ba4-138c-47ba-8372-4298e77ab5b8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
