<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Button Hitung Simulasi</name>
   <tag></tag>
   <elementGuidId>562bd0e5-88c8-46c9-8d21-84f9b34f06fe</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#id-hitung-simulasi</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='id-hitung-simulasi']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>a66e2820-0818-41cd-87f9-74d019cd191a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>id-hitung-simulasi</value>
      <webElementGuid>c9051418-849e-457a-992d-3f03d41305ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>relative flex whitespace-nowrap justify-center items-center px-4 gap-x-1.5 font-semibold bg-reliableBlack  h-[52px] text-base leading-[22px] rounded    text-white w-full lg:w-[328px] my-6 lg:my-0</value>
      <webElementGuid>c713bfcc-03c2-4928-a617-32fae2e1af30</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>7d31a7e9-d8d9-452c-98ed-74b8049e4127</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>HITUNG SIMULASI</value>
      <webElementGuid>fc0c7c03-8a65-4d75-a7a7-9ea4dea95ec7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;id-hitung-simulasi&quot;)</value>
      <webElementGuid>ea8c16a4-9529-4e45-8303-6e5571de3880</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='id-hitung-simulasi']</value>
      <webElementGuid>b15a8211-3c79-4d9d-bfcf-5ead09e26f4c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/main/div[2]/div/div[2]/section[2]/div/button</value>
      <webElementGuid>30043e9e-f6b0-43fe-956e-20f4e48ed65d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='MINTA PENAWARAN'])[1]/following::button[6]</value>
      <webElementGuid>c856c3a8-8589-4229-8173-2b1532c0b514</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pilih'])[2]/following::button[6]</value>
      <webElementGuid>130d27be-8259-44d5-b803-b299c3e0e0fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lihat Selengkapnya'])[1]/preceding::button[1]</value>
      <webElementGuid>43a28f6c-e83b-42ee-a0b8-d9c2299aed78</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section[2]/div/button</value>
      <webElementGuid>146b211f-0e63-4019-9b76-18d333c3e433</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'id-hitung-simulasi' and @type = 'submit' and (text() = 'HITUNG SIMULASI' or . = 'HITUNG SIMULASI')]</value>
      <webElementGuid>971be588-50ff-4219-bb4e-d7d337111e99</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
