<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Button Simulasi Kredit</name>
   <tag></tag>
   <elementGuidId>63e0fafe-7fde-46f7-ba48-262543aa6e27</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#id-simulasi-kredit</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='id-simulasi-kredit']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>4470ecf6-d7be-4c24-a88b-0212540dc0cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>id-simulasi-kredit</value>
      <webElementGuid>fefe5efd-0add-4f6f-ac53-81b81b319f6f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>relative flex whitespace-nowrap justify-center items-center px-4 gap-x-1.5 font-semibold bg-reliableBlack5  h-[52px] text-base leading-[22px] rounded    !text-[14px] w-1/3 text-black  lg:block hidden</value>
      <webElementGuid>3981a422-61d7-4d5c-b44c-307149c9309e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>08114f37-3ece-472c-ba62-61bb2d8dc68a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>SIMULASI KREDIT</value>
      <webElementGuid>70f7f71c-217b-413b-b6e9-7752b24bcfcd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;id-simulasi-kredit&quot;)</value>
      <webElementGuid>e74224f2-3a16-4f05-8a99-f21e00d3f536</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='id-simulasi-kredit']</value>
      <webElementGuid>efebdb3e-abb7-41c2-a0bd-cc4739534e25</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/main/section[2]/div/div[3]/div[2]/div[2]/div/button</value>
      <webElementGuid>d80c1224-9155-4142-9bc3-af5d28b2baa3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='UNDUH KATALOG'])[1]/following::button[1]</value>
      <webElementGuid>90825930-b977-4ed6-991c-29327c2916fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pilih'])[1]/following::button[1]</value>
      <webElementGuid>3a22d73a-eb1c-49ca-8207-dffc247951ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PRE ORDER'])[1]/preceding::button[1]</value>
      <webElementGuid>b57b9199-7a59-4b0f-9169-031930d85ec4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/button</value>
      <webElementGuid>a1ef3364-ded8-4a0c-b2ba-65a4eacb2a83</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'id-simulasi-kredit' and @type = 'submit' and (text() = 'SIMULASI KREDIT' or . = 'SIMULASI KREDIT')]</value>
      <webElementGuid>bee13083-3877-4357-9e7b-e995803fb8dc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
