<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_2x Serv. Kecil</name>
   <tag></tag>
   <elementGuidId>6a596854-48ef-4ea2-bc2a-71aa55adfb57</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='splide19-slide01']/div[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>6649c796-5766-44f3-8493-9195b01bec9f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-[14px] leading-[20px] text-black90  break-words overflow-hidden text-[14px] text-[#000] md:text-base font-normal px-4 lg:px-0 md:px-4</value>
      <webElementGuid>f53938e4-e793-4f08-943d-69fb5105c490</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>2x Serv. Kecil</value>
      <webElementGuid>32594b25-c857-44ea-a72f-0322e6042e7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;splide19-slide01&quot;)/div[@class=&quot;text-[14px] leading-[20px] text-black90  break-words overflow-hidden text-[14px] text-[#000] md:text-base font-normal px-4 lg:px-0 md:px-4&quot;]</value>
      <webElementGuid>d2974d9e-46e4-4011-aec6-b9f5b02b620f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='splide19-slide01']/div[2]</value>
      <webElementGuid>8afcb655-42fd-4ca8-926d-3da9566b30ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/div[2]</value>
      <webElementGuid>4dd0bfc5-d664-4ef1-a61a-d30cf8354527</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '2x Serv. Kecil' or . = '2x Serv. Kecil')]</value>
      <webElementGuid>77eb5c8f-ef26-48df-9c34-7af273a1fc7b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
