<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Button Edit</name>
   <tag></tag>
   <elementGuidId>4c10718c-f87d-4084-aa91-a75b0cad1b23</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='table-action-1']/div</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;table-action-1&quot;)/div[@class=&quot;hover- group flex cursor-pointer items-center space-x-2 rounded-md px-4 py-2 text-blue10 hover:bg-blue1 hover:text-blue7&quot;][count(. | //*[(text() = 'Edit' or . = 'Edit')]) = count(//*[(text() = 'Edit' or . = 'Edit')])]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>[data-testid=&quot;action-0&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>9a0b2bc2-9e87-450e-9433-f74bfac3839d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hover- group flex cursor-pointer items-center space-x-2 rounded-md px-4 py-2 text-blue10 hover:bg-blue1 hover:text-blue7</value>
      <webElementGuid>e96ec141-fdb7-443f-8050-ec102870a7d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>action-0</value>
      <webElementGuid>c0982324-ab82-429a-af7a-682553323d28</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Edit</value>
      <webElementGuid>cccb80a9-dd25-41e5-a381-e8541a3f2899</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;table-action-1&quot;)/div[@class=&quot;hover- group flex cursor-pointer items-center space-x-2 rounded-md px-4 py-2 text-blue10 hover:bg-blue1 hover:text-blue7&quot;]</value>
      <webElementGuid>77479400-c90d-4eb1-8b92-a3523b2b5e84</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='table-action-1']/div</value>
      <webElementGuid>d90e7034-2ba7-4105-9978-4d964a17d7e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='of'])[2]/following::div[15]</value>
      <webElementGuid>73969446-af6b-4b3f-aa73-773323ae4a89</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Page'])[1]/following::div[15]</value>
      <webElementGuid>8dfbac04-46dc-4554-a68d-87c2550b4cca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div</value>
      <webElementGuid>136b08cb-2347-4f7a-81cc-421194f12b22</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Edit' or . = 'Edit')]</value>
      <webElementGuid>1e93294b-8219-4b1c-b6ba-97c4881ace2e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
