<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Checkbox Uppercase</name>
   <tag></tag>
   <elementGuidId>baf13738-0ccd-43f7-bff1-73d9e0324cdd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;companyLetterHead&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='companyLetterHead']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Uppercase&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>89323a1b-2569-48c2-bacf-c2010ca90949</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>574d78fb-59e1-43ee-9056-5c6bfed11749</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>companyLetterHead</value>
      <webElementGuid>7d44281d-bf77-4e65-bdab-4883d4b3b9d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-5 h-5 border border-[#959595] rounded-[6px] focus:ring-0 checked:bg-red-600</value>
      <webElementGuid>e4dd44c3-77c8-4763-8a07-4048ba2d5e16</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>uppercase</value>
      <webElementGuid>7f900a2b-0475-496b-85e3-218a8bd855fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;children-wrapper&quot;)/div[1]/div[@class=&quot;flex flex-col gap-9&quot;]/div[@class=&quot;flex justify-center&quot;]/div[@class=&quot;w-[744px] relative&quot;]/div[@class=&quot;pb-0&quot;]/form[1]/div[@class=&quot;flex flex-col gap-7&quot;]/div[@class=&quot;grid grid-cols-2 gap-x-6 gap-y-3 p-6 border border-[#F6F6F6] rounded-lg shadow-sm&quot;]/div[@class=&quot;col-span-2 row-span-1&quot;]/div[1]/div[@class=&quot;flex flex-col gap-4&quot;]/div[@class=&quot;flex gap-6 tablet-size:flex-col md:flex-row&quot;]/label[@class=&quot;flex gap-2 items-center text-sm font-medium&quot;]/input[@class=&quot;w-5 h-5 border border-[#959595] rounded-[6px] focus:ring-0 checked:bg-red-600&quot;]</value>
      <webElementGuid>7329eadf-f2cb-4f17-9137-58c5d5ede062</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='companyLetterHead']</value>
      <webElementGuid>b8a25516-8ce2-4023-8768-3b1dab4419c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='children-wrapper']/div/div/div[2]/div/div/form/div/div/div[3]/div/div/div/label/input</value>
      <webElementGuid>da426ad4-66e1-4a72-8e45-43b643f7399b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label/input</value>
      <webElementGuid>16744b8f-ed3e-4f7a-a084-5693366a4804</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @name = 'companyLetterHead']</value>
      <webElementGuid>4219b1ba-307c-4ffb-9596-c58b4738b6ff</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
