<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Checkbox Number</name>
   <tag></tag>
   <elementGuidId>c946b17e-5488-4b4f-adde-3324e51a3923</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@name='companyLetterHead'])[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Number&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>badf673b-3788-43f7-a414-2f4617b45c3c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>8737a9fd-04da-491d-8c39-9df1643dc9a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>companyLetterHead</value>
      <webElementGuid>477540e3-8308-4b97-86e7-c32622f9b1d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-5 h-5 border border-[#959595] rounded-[6px] focus:ring-0 checked:bg-red-600</value>
      <webElementGuid>85255d89-1090-4b3d-9043-2d6e01aef7f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>2748327d-cbd7-4332-b66a-ee1b69c6442a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;children-wrapper&quot;)/div[1]/div[@class=&quot;flex flex-col gap-9&quot;]/div[@class=&quot;flex justify-center&quot;]/div[@class=&quot;w-[744px] relative&quot;]/div[@class=&quot;pb-0&quot;]/form[1]/div[@class=&quot;flex flex-col gap-7&quot;]/div[@class=&quot;grid grid-cols-2 gap-x-6 gap-y-3 p-6 border border-[#F6F6F6] rounded-lg shadow-sm&quot;]/div[@class=&quot;col-span-2 row-span-1&quot;]/div[1]/div[@class=&quot;flex flex-col gap-4&quot;]/div[@class=&quot;flex gap-6 tablet-size:flex-col md:flex-row&quot;]/label[@class=&quot;flex gap-2 items-center text-sm font-medium&quot;]/input[@class=&quot;w-5 h-5 border border-[#959595] rounded-[6px] focus:ring-0 checked:bg-red-600&quot;]</value>
      <webElementGuid>a9137090-41ac-401e-ad2a-def56164bd38</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@name='companyLetterHead'])[3]</value>
      <webElementGuid>4c8f0c1e-3a2d-4fa8-a4fc-e807daa9e3e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='children-wrapper']/div/div/div[2]/div/div/form/div/div/div[3]/div/div/div/label[3]/input</value>
      <webElementGuid>25157453-3e2a-4bdd-8be0-7fa4535a8e97</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label[3]/input</value>
      <webElementGuid>0562542b-2c65-49ad-b017-b22ba4178feb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @name = 'companyLetterHead']</value>
      <webElementGuid>00da18d7-3906-4cf9-83a3-7cac48360cf5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
