<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Submit</name>
   <tag></tag>
   <elementGuidId>55649640-f686-4e9b-b3f1-9f42651d1533</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#btn-submit-interest</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='btn-submit-interest']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>0d5e07fb-79c4-4052-b7e2-a3411a3b5e61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>flex justify-end items-center p-3 gap-x-3 text-base font-bold md:p-4 md:justify-center md:flex-1 md:rounded   cursor-default  bg-reliableBlack20  w-full text-[#FFFEFE] p-4</value>
      <webElementGuid>5dcfa541-1d53-4259-b80d-9085d7944f92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btn-submit-interest</value>
      <webElementGuid>b65b2837-5ac6-46cf-9186-55fe347cfe9f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>variant</name>
      <type>Main</type>
      <value>bg-supportiveRed</value>
      <webElementGuid>2a58638f-eae8-442a-a499-5021e0034702</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Submit</value>
      <webElementGuid>178a7e70-9bf2-47cd-a5d2-7857f8fe6b63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btn-submit-interest&quot;)</value>
      <webElementGuid>ee12d246-10c8-4b80-a50e-e3987952012e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='btn-submit-interest']</value>
      <webElementGuid>024adb50-560a-4bf7-9aee-5e5d7f28ce88</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/main/div[8]/div/div[2]/form/div[7]/button</value>
      <webElementGuid>0a21a628-8e03-469c-acd7-f25ec0184f98</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/button</value>
      <webElementGuid>1e305ca3-a115-4203-85e2-c69c353cfdca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'btn-submit-interest' and (text() = 'Submit' or . = 'Submit')]</value>
      <webElementGuid>4d026cfb-2ea4-469f-862e-7ce186234b7a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
