<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Kota_product-dd-city</name>
   <tag></tag>
   <elementGuidId>5479f4c5-a6df-4957-9b17-883f8e2b1d3c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#product-dd-city</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='product-dd-city']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>18b6bac6-69ac-48ef-a220-44e959d362b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>product-dd-city</value>
      <webElementGuid>a49a372d-86c7-4393-8cfd-56a9179dd540</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>fa08227b-2882-491d-bd75-6f1be0be0408</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-full outline-none px-4 py-2 bg-reliableBlack3 placeholder:text-reliableBlack60 text-reliableBlack border-b border-reliableBlack30 focus:border-reliableBlack60 lg:px-5 lg:py-4 px-5 py-3.5 text-reliableBlack max-h-fit bg-reliableBlack3 placeholder:text-[#777777] lg:max-h-fit lg:text-reliableBlack cursor-pointer</value>
      <webElementGuid>e9b249c6-36ed-4aca-93fa-f7302e2860cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Pilih Kota</value>
      <webElementGuid>ef89e6f5-2534-45e4-ae9a-620e96573515</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Jakarta Pusat</value>
      <webElementGuid>b3a212f8-53e5-4619-bc85-a069241b6459</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;product-dd-city&quot;)</value>
      <webElementGuid>95a3b6f1-b445-4162-a335-c6a5bed534f3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='product-dd-city']</value>
      <webElementGuid>b8c93018-5301-4053-87fb-892cd2a29474</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/main/div[8]/div/div[2]/form/div[3]/div/div/input</value>
      <webElementGuid>31f5eede-71ba-48b7-9f72-e9d156c74341</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/input</value>
      <webElementGuid>cd2f4c9f-1581-46ad-ab26-e567134fd782</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'product-dd-city' and @type = 'text' and @placeholder = 'Pilih Kota']</value>
      <webElementGuid>b4cc4fba-7c5a-4200-a47b-a16a656dec23</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
