<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Model Mobil</name>
   <tag></tag>
   <elementGuidId>6c6ddbf0-9a88-49a3-8cd5-91e78504521f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#dd-model-mobil</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='dd-model-mobil']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c491352f-d60f-4694-82f8-4ecddae03dab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dd-model-mobil</value>
      <webElementGuid>46094c2f-7eca-418a-8348-ba3b9c269e7e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>7418354d-7608-427c-bd21-cb22ccdadf7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-full outline-none px-4 py-2 bg-reliableBlack3 placeholder:text-reliableBlack60 text-reliableBlack border-b border-reliableBlack30 focus:border-reliableBlack60 lg:px-5 lg:py-4 bg-white border-[#5F5F5F] max-h-fit lg:max-h-fit focus:border-reliableBlack false cursor-pointer</value>
      <webElementGuid>f15a4731-a73c-41a3-8b6c-76b43671671e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Pilih Mobil</value>
      <webElementGuid>61c6d4cb-5d34-40e7-b81b-d7dca84cc9b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dd-model-mobil&quot;)</value>
      <webElementGuid>fd90a7e2-f134-4611-a610-ed0c8af4f645</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='dd-model-mobil']</value>
      <webElementGuid>1dfcfbfb-b7f1-4774-a948-3edbb89b8e73</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/main/div[2]/div/div/div[2]/div/section/form/div[2]/div/div/input</value>
      <webElementGuid>a1493238-a786-4192-80c0-ed9db1c96e8c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/input</value>
      <webElementGuid>dae15759-f917-43f6-ac70-3d17f599f11a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'dd-model-mobil' and @type = 'text' and @placeholder = 'Pilih Mobil']</value>
      <webElementGuid>ea8c5f27-b1c8-49a6-bed5-b9bdbfa0e78c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
