<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Nama Lengkap</name>
   <tag></tag>
   <elementGuidId>1b8e4e8e-9f03-40e8-b9b7-745a2d10cc25</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input-full-name</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input-full-name']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5524f211-13c8-46c6-9d8d-a18c90afa85b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-full-name</value>
      <webElementGuid>d1185308-a712-4268-bfd3-6b1eb4e9540a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Nama Depan dan Belakang</value>
      <webElementGuid>7632cdb6-24eb-4135-8a55-a966d18944b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>ab60e8b3-eec5-4b91-9af8-deb76fa7775f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>60</value>
      <webElementGuid>6c0f5c8c-ba51-4854-b7e0-8581d7c723ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-full outline-none null bg-reliableBlack3 text-reliableBlack border-b border-reliableBlack30 placeholder:text-reliableBlack60 focus:border-reliableBlack60 false w-full px-4 py-2 lg:px-5 lg:py-4 max-h-[30px] lg:max-h-[40px] text-base lg:text-base leading-4 bg-white border-[#5F5F5F] max-h-fit lg:max-h-fit focus:border-reliableBlack false null  focus:outline-none</value>
      <webElementGuid>aef11b55-38fb-4264-a426-189e463cfe90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-full-name&quot;)</value>
      <webElementGuid>4ac072ca-bdd8-428c-b8cf-254291664e97</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-full-name']</value>
      <webElementGuid>a590ffe1-9fcf-43b3-96c4-b8c21d054543</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/main/div[2]/div/div/div[2]/div/section/form/div/div/div/div/div/input</value>
      <webElementGuid>f8762f6b-40df-44c5-aeaf-894101ba89e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div/div/div/div/input</value>
      <webElementGuid>3f917471-4d0e-4cd8-a059-20de812b0867</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'input-full-name' and @placeholder = 'Nama Depan dan Belakang' and @type = 'text']</value>
      <webElementGuid>36d9c987-403d-4f61-8e73-6a263ea25261</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
