<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>No Hp</name>
   <tag></tag>
   <elementGuidId>3f7d7a99-a784-4230-bb1d-fc188bdefd25</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input-phone-number</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input-phone-number']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9ce9b17a-4dc2-4ac5-ac7c-79002da69005</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-phone-number</value>
      <webElementGuid>565c88eb-f61d-4ebc-9d8b-5883a662fd7a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>XXX-XXX-XXX</value>
      <webElementGuid>37ad596b-e1dd-41ca-997d-6db53a92d91f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>f210c731-de2a-433a-8c71-ee289173372e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-full outline-none null bg-reliableBlack3 text-reliableBlack border-b border-reliableBlack30 placeholder:text-reliableBlack60 focus:border-reliableBlack60 false w-full px-4 py-2 lg:px-5 lg:py-4 max-h-[30px] lg:max-h-[40px] text-base lg:text-base leading-4 bg-white border-[#5F5F5F] max-h-fit lg:max-h-fit focus:border-reliableBlack false !pl-1 null  focus:outline-none</value>
      <webElementGuid>f210f050-861c-4f0d-a8b3-ba13f02fffb3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>pattern</name>
      <type>Main</type>
      <value>[0-9]*</value>
      <webElementGuid>340234ef-d1bb-4625-9e1c-3f1c3d6563c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>inputmode</name>
      <type>Main</type>
      <value>numeric</value>
      <webElementGuid>ebdf3fc1-c3f9-4824-9ee6-778ca10ccd1e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>min</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>1f9d8394-ff40-4919-b2a7-f91b53f01171</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-phone-number&quot;)</value>
      <webElementGuid>f02a67cc-cae2-4424-9b51-630af6ad4db1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-phone-number']</value>
      <webElementGuid>77f83947-576a-45b1-adb7-2679e69eca56</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/main/div[2]/div/div/div[2]/div/section/form/div/div[2]/div/div/div/input</value>
      <webElementGuid>30835340-1fc9-4406-becc-298d7269e360</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div[2]/div/div/div/input</value>
      <webElementGuid>eaf6d8e0-f153-42b1-8616-0d65a642db39</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'input-phone-number' and @placeholder = 'XXX-XXX-XXX' and @type = 'number']</value>
      <webElementGuid>a1e79c8e-f833-4f13-8887-44edbe1341b6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
