<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Sub Menu Pembayaran</name>
   <tag></tag>
   <elementGuidId>ae417375-0518-4480-a411-3b493d41f824</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@data-testid = 'sidebar-menu-pembayaran']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//a[@href='/report/payment'])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Pembayaran&quot;i] >> nth=2</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>382dd1ac-43d6-4304-9705-ec8f28385b42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-sm py-[10px] pl-9 font-normal text-neutral10 hover:text-blue8</value>
      <webElementGuid>fd5a1f4a-e6ca-4a17-817b-b8f658fbfefa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>sidebar-menu-pembayaran</value>
      <webElementGuid>302847e7-7476-4efd-bbf7-908b37895db6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Pembayaran</value>
      <webElementGuid>7145b6e7-892f-45fa-a4d3-31ac4442f907</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;min-w-screen relative flex min-h-screen overflow-hidden transition-opacity duration-500 ease-in-out&quot;]/section[@class=&quot;border-neutral-5 z-50 h-screen w-full max-w-[234px] border-r border-neutral5 bg-neutral1 px-4 py-6&quot;]/div[@class=&quot;mt-[52px] flex flex-col gap-2&quot;]/div[3]/div[@class=&quot;overflow-hidden transition-all duration-300 max-h-96&quot;]/a[2]/p[@class=&quot;text-sm py-[10px] pl-9 font-normal text-neutral10 hover:text-blue8&quot;]</value>
      <webElementGuid>a6fd712d-f045-4ef5-bc5a-6c06a34b8f17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/report/payment</value>
      <webElementGuid>992214a2-0c39-4a85-a435-655710da6c26</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/section/div/div[3]/div[2]/a[2]/p</value>
      <webElementGuid>1af4457f-8841-47f2-9574-b4ddc575087c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Beranda'])[3]/preceding::p[7]</value>
      <webElementGuid>957f6dda-dee1-48e5-b4b7-3d4731ee61b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Siswa Aktif'])[1]/preceding::p[8]</value>
      <webElementGuid>f5cba6e2-2fa7-415d-849b-443aea8f6f22</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/a[2]/p</value>
      <webElementGuid>7053ce54-3505-492f-922d-882f0f782c07</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'Pembayaran' or . = 'Pembayaran')]</value>
      <webElementGuid>1e83e191-3b73-4ae6-b11a-22454e7909f0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
