<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Button View Logo</name>
   <tag></tag>
   <elementGuidId>9e482937-367b-41c2-81f1-be1434deb13a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='children-wrapper']/div/div/div[2]/div/div/form/div/div/div[4]/div/div/div[2]/div[2]/label</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;View&quot;s</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>b2061afb-f52a-4c23-8a09-5682b45ee72f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>inline-block text-[10px] md:text-[12px] 2xl:text-[16px] xl:text-[14px] font-semibold px-3 py-2 bg-[#4C79AB] text-white rounded-md cursor-pointer hover:bg-[#48709d] focus:outline-none focus:ring-2 focus:ring-blue-500 w-max text-center</value>
      <webElementGuid>f7653572-c82a-4662-a78c-729c0ea235ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>View</value>
      <webElementGuid>a4d912c5-fd8b-4b4a-aa9d-6673856b766c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;children-wrapper&quot;)/div[1]/div[@class=&quot;flex flex-col gap-9&quot;]/div[@class=&quot;flex justify-center relative&quot;]/div[@class=&quot;w-[744px]&quot;]/div[@class=&quot;pb-0&quot;]/form[1]/div[@class=&quot;flex flex-col gap-7&quot;]/div[@class=&quot;grid grid-cols-2 gap-x-6 gap-y-3 p-6 border border-[#F6F6F6] rounded-lg shadow-sm&quot;]/div[@class=&quot;col-span-2 row-span-1&quot;]/div[1]/div[@class=&quot;flex flex-col gap-1 overflow-x-hidden&quot;]/div[@class=&quot;p-4 border-dashed border-2 border-[#dbdbdb] w-full h-[120px] md:h-auto xl:h-auto rounded-md shadow-sm bg-[#F5F5F5] flex gap-2 flex-col lg:flex-row itm items-start lg:items-center justify-between&quot;]/div[@class=&quot;flex flex-col&quot;]/label[@class=&quot;inline-block text-[10px] md:text-[12px] 2xl:text-[16px] xl:text-[14px] font-semibold px-3 py-2 bg-[#4C79AB] text-white rounded-md cursor-pointer hover:bg-[#48709d] focus:outline-none focus:ring-2 focus:ring-blue-500 w-max text-center&quot;]</value>
      <webElementGuid>e68f606b-781e-495d-87a2-28244ff31424</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='children-wrapper']/div/div/div[2]/div/div/form/div/div/div[4]/div/div/div[2]/div[2]/label</value>
      <webElementGuid>172596c5-d22d-470e-b132-dc43da498e82</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Change File'])[1]/following::label[1]</value>
      <webElementGuid>fa2628c9-b099-4b7d-a0ad-dbb51b72b44e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='View']/parent::*</value>
      <webElementGuid>ec5b85d4-12e5-4f14-841f-f6a6a28e3a96</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/label</value>
      <webElementGuid>bfdb4033-5acc-458a-b5a9-d3e547aa3a2a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = 'View' or . = 'View')]</value>
      <webElementGuid>16c7b664-d45f-41b6-972e-4b07d26f81f4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
