<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Button Cancel</name>
   <tag></tag>
   <elementGuidId>cf57f6dd-6041-463a-9cbd-0dd695b5e83c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@type='button']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Cancel&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>e10d42ed-1fbe-438f-8dc6-f92a431a4ff5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>781dd4c2-fc4a-4aca-9df0-e39ced03ab59</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>cursor-pointer rounded-md flex gap-1 items-center justify-center w-[120px] h-[44px] border border-[#C7C8C9] false</value>
      <webElementGuid>0dd521d1-43f1-4458-8d90-87da6e362173</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Cancel</value>
      <webElementGuid>0bf26577-1b6b-47a5-9be4-47c1b7d166ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;children-wrapper&quot;)/div[1]/div[@class=&quot;flex flex-col gap-9&quot;]/div[@class=&quot;flex justify-center relative&quot;]/div[@class=&quot;w-[744px]&quot;]/div[@class=&quot;pb-0&quot;]/form[1]/div[@class=&quot;flex flex-col gap-7&quot;]/div[@class=&quot;flex justify-between z-50&quot;]/div[@class=&quot;flex gap-2&quot;]/button[@class=&quot;cursor-pointer rounded-md flex gap-1 items-center justify-center w-[120px] h-[44px] border border-[#C7C8C9] false&quot;]</value>
      <webElementGuid>8e482aad-9c34-49c0-b455-39a3bedcf840</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@type='button']</value>
      <webElementGuid>48f19542-6dc0-4a5e-98b1-029565dabbe0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='children-wrapper']/div/div/div[2]/div/div/form/div/div[2]/div/button</value>
      <webElementGuid>04d44fb5-b41c-4d84-b3da-6b7f84b26601</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='View'])[1]/following::button[1]</value>
      <webElementGuid>a6061102-47da-42f2-b639-4fe37669a505</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Change File'])[1]/following::button[1]</value>
      <webElementGuid>5b790f9f-d3e7-47c4-9ab5-539c05873156</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>81fc4974-09fb-45e7-bbb2-f3a7c4cc2204</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Cancel' or . = 'Cancel')]</value>
      <webElementGuid>519c65ee-8532-46d5-b3d2-4cf471570dfa</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
