<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Upload Others</name>
   <tag></tag>
   <elementGuidId>9c90ca7e-2191-4100-a070-5fc30a4d928d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='children-wrapper']/div/div/div[2]/form/div/div/div[2]/div[4]/div/div/div[2]/div[2]/label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Upload File&quot;i >> nth=4</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>a2c0df08-c88b-4baf-99ee-8de75b5e8ff8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>others</value>
      <webElementGuid>6b602144-7ec8-4a31-ac33-9c96a0a450bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>inline-block text-[10px] md:text-[12px] 2xl:text-[16px] xl:text-[14px] font-semibold px-3 py-2 bg-[#4C79AB] text-white rounded-md cursor-pointer hover:bg-[#48709d] focus:outline-none focus:ring-2 focus:ring-blue-500 w-max text-center</value>
      <webElementGuid>f793a3d1-f8db-4241-92a4-246a54846e27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Upload File</value>
      <webElementGuid>8e4ac3e1-866b-4aae-9e0f-11ca755087f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;children-wrapper&quot;)/div[@class=&quot;flex justify-center&quot;]/div[@class=&quot;flex flex-col gap-7 w-[508px] md:w-full&quot;]/div[@class=&quot;pb-[100px]&quot;]/form[1]/div[@class=&quot;flex flex-col gap-7&quot;]/div[@class=&quot;flex flex-col gap-6&quot;]/div[@class=&quot;p-6 border border-[#F6F6F6] rounded-lg shadow-sm grid grid-cols-2 gap-x-6 gap-y-4&quot;]/div[@class=&quot;col-span-1 row-span-1&quot;]/div[1]/div[@class=&quot;flex flex-col gap-1 overflow-x-hidden&quot;]/div[@class=&quot;p-4 border-dashed border-2 border-[#dbdbdb] w-full h-[120px] md:h-auto xl:h-auto rounded-md shadow-sm bg-[#F5F5F5] flex gap-2 flex-col lg:flex-row itm items-start lg:items-center justify-between&quot;]/div[@class=&quot;flex flex-col&quot;]/label[@class=&quot;inline-block text-[10px] md:text-[12px] 2xl:text-[16px] xl:text-[14px] font-semibold px-3 py-2 bg-[#4C79AB] text-white rounded-md cursor-pointer hover:bg-[#48709d] focus:outline-none focus:ring-2 focus:ring-blue-500 w-max text-center&quot;]</value>
      <webElementGuid>4cbdf847-18b9-41fa-acba-1fe6685d8342</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='children-wrapper']/div/div/div[2]/form/div/div/div[2]/div[4]/div/div/div[2]/div[2]/label</value>
      <webElementGuid>1a7b37c8-56ae-4a47-9ea0-d839e7b1d91d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Format File: PDF, JPEG, JPG, PNG, XLSX, PPT and DOC'])[1]/following::label[1]</value>
      <webElementGuid>8f85a5d5-50ed-4294-a9fb-dac6024e4182</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div[2]/div[2]/label</value>
      <webElementGuid>13097fde-f6ac-4114-a52d-0219fa56b627</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = 'Upload File' or . = 'Upload File')]</value>
      <webElementGuid>77a6c199-0d58-48e9-a769-4985f36e0bfa</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
