<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Field Amount To</name>
   <tag></tag>
   <elementGuidId>35be62e1-d0c7-453c-9bc4-911b8e7afff0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='amount_to_filter']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;amount_to_filter&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>input[name=&quot;amount_to_filter&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4b277c6e-bf0b-4c53-a3c7-f9dce09990a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>7167864c-3a49-4cc4-899e-5ae4a59499e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>amount_to_filter</value>
      <webElementGuid>6ddbd63b-7560-4956-b593-988da131d663</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Number</value>
      <webElementGuid>2bd358da-0015-4352-a7b9-0bfe703de7fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-full px-3 h-[52px] flex items-center placeholder:text-[#DEDEDE] focus:outline-none rounded-md  false</value>
      <webElementGuid>9ff459ec-a33b-4767-84b1-62879acd836b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>max</name>
      <type>Main</type>
      <value>100</value>
      <webElementGuid>42f36913-8c45-4550-9f92-942c8b37a065</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;children-wrapper&quot;)/div[@class=&quot;flex justify-between&quot;]/div[@class=&quot;w-[768px] md:w-full&quot;]/div[1]/div[2]/div[@class=&quot;w-full&quot;]/div[@class=&quot;fixed inset-0 bg-gray-800 bg-opacity-50 flex justify-center items-center z-50&quot;]/div[@class=&quot;w-full max-w-[552px] rounded-lg border border-[#D3D2D2] bg-white&quot;]/div[@class=&quot;max-h-[85vh] overflow-auto&quot;]/form[1]/div[@class=&quot;p-6 pb-4 flex flex-col gap-5&quot;]/div[@class=&quot;flex flex-col gap-2&quot;]/div[@class=&quot;flex items-center gap-5&quot;]/div[3]/div[1]/div[@class=&quot;relative w-full flex flex-col gap-1 w-full&quot;]/div[@class=&quot;null border border-[#DEDEDE] rounded-md text-black bg-white&quot;]/input[@class=&quot;w-full px-3 h-[52px] flex items-center placeholder:text-[#DEDEDE] focus:outline-none rounded-md  false&quot;]</value>
      <webElementGuid>26b790ab-011a-44c0-b89e-d2a45b032beb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='amount_to_filter']</value>
      <webElementGuid>b5c97a68-9421-4826-af4c-69964aa87ec2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='children-wrapper']/div/div/div/div[2]/div/div[4]/div/div[2]/form/div/div[5]/div/div[3]/div/div/div[2]/input</value>
      <webElementGuid>e61128f1-5665-41ef-8dbd-2b3403d400a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div[3]/div/div/div[2]/input</value>
      <webElementGuid>9afb1ec0-b483-4c84-9843-a5c4ad3d1439</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'amount_to_filter' and @placeholder = 'Number']</value>
      <webElementGuid>b97c005d-b531-49f5-8331-045ce2696994</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
