<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Button Pilih</name>
   <tag></tag>
   <elementGuidId>510625aa-56e3-407e-98a1-80f8b03b482c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#id-pilih-variant</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;id-pilih-variant&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>1689f94f-dfcc-4459-8afb-41e62458db4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>flex justify-end items-center p-3 gap-x-3 text-base font-bold md:p-4 md:justify-center md:flex-1 md:rounded     bg-supportiveRed text-white text-center w-full md:mt-8 p-5 md:p-4 h-[56px]</value>
      <webElementGuid>d54fbcbb-1969-4fcb-95e5-30f28af6b04b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>id-pilih-variant</value>
      <webElementGuid>abbe4102-cb0b-4833-92a7-b6e2f306593e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>variant</name>
      <type>Main</type>
      <value>bg-supportiveRed</value>
      <webElementGuid>0a034178-3871-4077-b9a2-c5fa5f5e4b07</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Pilih</value>
      <webElementGuid>2d1f1ea4-9d6b-4582-b933-b81a0dce582f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/main[@class=&quot;bg-white&quot;]/section[2]/div[@class=&quot;md:container py-4  px-0&quot;]/div[@class=&quot;opacity-100 duration-300 ease-in-out fixed w-[100vw] h-[100vh] z-[70] top-1/2 left-1/2 transform -translate-x-1/2 -translate-y-1/2 bg-opacity-30 bg-black&quot;]/div[@class=&quot;lg:max-h-[80vh] false duration-300 ease-in-out flex flex-col absolute bg-white rounded top-1/2 left-1/2 transform -translate-x-1/2 -translate-y-1/2&quot;]/div[@class=&quot;px-6 py-6 w-[622px]&quot;]/div[@class=&quot;flex flex-1 flex-col items-stretch w-full mx-auto md:mb-0 mb-4 md:mt-0 mt-3&quot;]/div[2]/button[@id=&quot;id-pilih-variant&quot;]</value>
      <webElementGuid>8fb15434-7c8b-4317-977d-f3bafd636883</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='id-pilih-variant']</value>
      <webElementGuid>ec3a0b6f-5590-4c70-8926-716eb6c5ceb9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/main/section[2]/div/div[2]/div/div[2]/div/div[2]/button</value>
      <webElementGuid>f85e2aae-ce1c-4f43-91ba-f6a5c9ea3e97</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='HUBUNGI ACCOUNT EXECUTIVE KAMI'])[1]/following::button[1]</value>
      <webElementGuid>4de62b88-5803-49b3-ac06-eb360cf0d14d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bingung memilih tipe yang sesuai?'])[1]/following::button[1]</value>
      <webElementGuid>5fad5633-c104-4e5b-830e-b2c634c6b72e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='UNDUH KATALOG'])[1]/preceding::button[1]</value>
      <webElementGuid>8096dbd2-6266-462d-9924-45498d455420</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/button</value>
      <webElementGuid>33b5713a-0ec1-4add-a23e-0fc9122743c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'id-pilih-variant' and (text() = 'Pilih' or . = 'Pilih')]</value>
      <webElementGuid>92213473-4a6c-4557-a373-a61e96e905c5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
