<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Regression CIty</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>1</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>true</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>56f9cd45-4496-4569-9253-25c8e85d3ef7</testSuiteGuid>
   <testCaseLink>
      <guid>8bcce793-b5ef-4096-9cb8-d932c776a925</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Landing Page/CIty Landing Page/Landing Page City</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7eede03b-d329-4d5c-be2d-486c9415db0d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>76363d56-86a2-46bf-96a5-06434dd04459</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6c521129-a860-438f-a9ed-d0c5f0898c57</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>bddc7d75-e7d5-4c36-849d-cfcb70865685</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Landing Page/CIty Landing Page/Filter Showroom</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>11fba498-2e65-4a19-a9b5-a0b5aa72f7d0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e11f3496-33f6-46d6-8e61-a0a31a0ecd51</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>31cfd2f3-dbef-46c5-a006-93d2f17d7e33</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Landing Page/CIty Landing Page/Direct Map</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7bfdf442-ce1f-4491-a52e-eec5362c8c03</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>ba46ca78-0d25-4354-a6a4-24f0ee638e4b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Landing Page/CIty Landing Page/List View</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f0d302e7-e175-4352-968e-58358f2d8153</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>91728bd5-174e-4788-95b6-ac46d9c19fa0</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>eeb0ab9f-34a1-4d62-a90b-78e0c47114db</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Landing Page/CIty Landing Page/Minta Penawaran</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1a5e8cc1-a67e-4303-8b66-388915ce6160</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>6c607949-ada9-43fa-a386-829e89f0f357</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Landing Page/CIty Landing Page/Inquiry News City</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d5f9e48e-c265-4518-b8b6-7dbb95ef2bb0</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>fe1c7135-4ea0-4c82-8aeb-ed09a86ae6db</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Landing Page/CIty Landing Page/Inquiry Mobil Baru Promo City</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>decae318-eb08-4c59-a691-25619a03e059</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>fb6fc6f0-d051-4282-a2a2-a10ff5f99b93</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Landing Page/CIty Landing Page/Detail Promo by landing page city</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e811ec2a-f267-49ac-9933-ec16a9807ff7</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>acee2c5e-744b-4ad3-9351-fd6bb5c0ed00</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Landing Page/CIty Landing Page/Detail News by landing page city</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>decf13ff-2da8-4a81-8aa5-1105b3066a36</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>bbcc3b84-5dad-4562-ab9d-1d8d97c5ae7a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Landing Page/CIty Landing Page/Negative Case Minta Penawaran</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e5d710df-9871-436e-bb5b-f1bb76ebf504</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
