<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_Bulk.xlsx</name>
   <tag></tag>
   <elementGuidId>a5bf6bc0-97e0-43a4-868a-7f8a1222b9e4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='modal']/div[2]/div/div/div[2]/div/div/div/p</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>p.text-sm.leading-4</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>[data-testid=&quot;upload-file-name&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>5eb8d275-7cd5-4e05-bb74-967cbd6b31eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-sm leading-4</value>
      <webElementGuid>13eb1baf-f55f-43b6-8e7d-2b83178aa9ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>upload-file-name</value>
      <webElementGuid>5cbc33e2-197a-4f52-9616-d5b7eb0379c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Bulk.xlsx</value>
      <webElementGuid>acdb8c9e-7a4d-46fb-829d-21623a8ecc41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;modal&quot;)/div[@class=&quot;max-h-[calc(100dvh-128px)] overflow-auto p-6 px-6 pt-6 pb-0 break-words&quot;]/div[@class=&quot;flex flex-col gap-5&quot;]/div[@class=&quot;flex flex-col gap-1&quot;]/div[@class=&quot;flex items-center justify-between rounded-md border-2 px-6 py-[21px] border-[#b7b7b7] gap-x-2 border-dashed&quot;]/div[@class=&quot;flex gap-x-4&quot;]/div[@class=&quot;flex flex-col gap-y-[2px]&quot;]/div[@class=&quot;flex gap-x-2 break-all&quot;]/p[@class=&quot;text-sm leading-4&quot;]</value>
      <webElementGuid>8e83f92c-1f88-40a9-91c3-6dc42da8b0ee</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modal']/div[2]/div/div/div[2]/div/div/div/p</value>
      <webElementGuid>21d89f47-26a1-4f86-8616-cfbb3d5957c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Scan File'])[1]/following::p[3]</value>
      <webElementGuid>ca923e06-f87b-4d31-a86a-1fc2aea8ae50</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='`'])[1]/following::p[3]</value>
      <webElementGuid>03532d3d-9759-4050-a13b-65df2cfbb3ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Change File'])[1]/preceding::p[1]</value>
      <webElementGuid>bcec43c6-b95a-4084-aff4-57cd7d1ded9f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lihat'])[1]/preceding::p[2]</value>
      <webElementGuid>ec4b52c5-37db-411c-909b-6bb3a3f6363e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Bulk.xlsx']/parent::*</value>
      <webElementGuid>24587489-25e0-49d7-885d-de1abc56ad12</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[2]/div/div/div/p</value>
      <webElementGuid>0f243154-0658-4c6d-bc12-1a5aa7d16380</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'Bulk.xlsx' or . = 'Bulk.xlsx')]</value>
      <webElementGuid>b92cb178-a94c-4f44-8fac-79d8132cdd1e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
