<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Field Tempat Lahir</name>
   <tag></tag>
   <elementGuidId>dd84c3e2-997c-49f0-921b-e97aba10656f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='birthPlace']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;birthPlace&quot;]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@type = 'text' and @name = 'birthPlace']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Masukkan tempat lahir&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9ebf5838-e202-4689-983c-90d1ac500f84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>3edd8f5c-a6c6-4a6f-be49-08d2392ca41e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Masukkan tempat lahir</value>
      <webElementGuid>b8c9deff-b35b-461a-b6dc-ba9a43280b5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>h-full w-full rounded-md px-3 text-base placeholder:text-neutral6 focus:outline-none cursor-auto</value>
      <webElementGuid>9b37c123-5730-4f6b-abb7-f97ec7eeaa2f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>birthPlace</value>
      <webElementGuid>f1b69ad2-46b9-45d6-86ce-417681b07fae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>100</value>
      <webElementGuid>77d4e4a2-e753-47e9-8e43-52f17db31ec3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;layout-content&quot;)/div[@class=&quot;flex h-full flex-col overflow-auto&quot;]/div[@class=&quot;grow px-10&quot;]/form[1]/div[@class=&quot;grid grid-cols-2 gap-x-6 gap-y-4&quot;]/div[@class=&quot;flex gap-6&quot;]/div[@class=&quot;flex w-full flex-col gap-1&quot;]/div[@class=&quot;group relative flex h-[52px] w-full items-center gap-[10px] rounded-md border border-neutral5 bg-white focus-within:border-blue6 hover:border-blue6&quot;]/input[@class=&quot;h-full w-full rounded-md px-3 text-base placeholder:text-neutral6 focus:outline-none cursor-auto&quot;]</value>
      <webElementGuid>755fb3ea-e15d-483f-8091-77a774133f7b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='birthPlace']</value>
      <webElementGuid>3f6f3967-0428-42c7-9e26-5a64210106a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='layout-content']/div[2]/div/form/div/div[3]/div/div[2]/input</value>
      <webElementGuid>e8c9ae3c-fc1a-4f90-a79a-280c963ff87c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div[2]/input</value>
      <webElementGuid>91bc8bb2-f519-49de-924f-ff421b7173fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'Masukkan tempat lahir' and @name = 'birthPlace']</value>
      <webElementGuid>750ac756-479e-4a79-aa4c-edbb870d3027</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
