<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Value Masuk Sebagai BPJPH</name>
   <tag></tag>
   <elementGuidId>9f50fe31-ec2c-4c91-87fc-23b4b7494212</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[(text() = 'BPJPH' or . = 'BPJPH')]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div/div[2]/div/div/div/div/div/div/div/div[2]/div[3]</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>div >> internal:has-text=/^Pendamping Halal$/</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>3089f802-6154-40ac-a7b4-c6b42fce71dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>px-3 py-2 hover:bg-gray-200 cursor-pointer flex items-center</value>
      <webElementGuid>f5dad976-6f45-4df4-9df5-4f872ce229b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>BPJPH</value>
      <webElementGuid>4791a1ed-a597-4883-8deb-ffac91c9ec57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;__className_d65c78&quot;]/div[@class=&quot;fixed inset-0 bg-gray-800 bg-opacity-50 flex justify-center items-center z-[9999] overflow-y-auto&quot;]/div[@class=&quot;w-96 max-w-[552px] m-4 lg:m-0 rounded-lg border border-[#D3D2D2] bg-white overflow-auto max-h-none md:max-h-[90vh] p-4 md:p-6 w-screen md:w-auto md:h-auto mx-2 !overflow-visible&quot;]/div[@class=&quot;flex flex-col gap-y-1 text-center items-center justify-center mb-5&quot;]/div[@class=&quot;w-full flex flex-row items-center mt-0 lg:mt4 justify-between gap-x-2&quot;]/div[@class=&quot;w-8/12 md:w-6/12&quot;]/div[@class=&quot;w-full&quot;]/div[@class=&quot;flex flex-col gap-1 relative w-full&quot;]/div[@class=&quot;relative&quot;]/div[@class=&quot;-translate-y-[calc(140%)] absolute z-[999] mt-1 w-full bg-white border border-[#DEDEDE] rounded-md shadow-lg max-h-60 overflow-y-auto&quot;]/div[@class=&quot;px-3 py-2 hover:bg-gray-200 cursor-pointer flex items-center&quot;]</value>
      <webElementGuid>0e5ce5ea-9c27-4239-a3fd-4f522d903e58</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div[2]/div/div/div/div/div/div/div/div[2]/div[3]</value>
      <webElementGuid>36a3726f-5043-49b0-b2ef-338812230401</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Masuk sebagai'])[6]/following::div[5]</value>
      <webElementGuid>b5d48a17-7f63-45be-9edd-c48855b0fa02</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Masuk sebagai'])[5]/following::div[11]</value>
      <webElementGuid>68c3e65d-3040-491e-9cd4-493f40417e21</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[3]</value>
      <webElementGuid>f793816e-982b-493a-9bd2-6d15d1b9f203</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Pendamping Halal' or . = 'Pendamping Halal')]</value>
      <webElementGuid>4ba9c15d-5c68-4eb8-90b7-024f7ad0814d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
